from BaseClasses import Item, ItemClassification
from typing import NamedTuple, Any

class SKPDItem(Item):
    game: str = "Shovel Knight Pocket Dungeon"

class SKPDItemData(NamedTuple):
    code: int
    category: str
    classification: ItemClassification
    data: Any = None

def get_item_from_category(category: str) -> list:
    itemlist = []
    for item in skpd_items:
        if skpd_items[item].category == category:
            itemlist.append(item)
    return itemlist

skpd_items: dict[str, SKPDItemData] = {
    "Shop Restock":             SKPDItemData(101, "Progression", ItemClassification.progression_skip_balancing),
    "Key Fragment":             SKPDItemData(102, "Progression", ItemClassification.progression),
    "Progressive Dungeon":      SKPDItemData(103, "Progression", ItemClassification.progression),

    "Shovel Knight":            SKPDItemData(104, "Character", ItemClassification.progression),
    "King Knight":              SKPDItemData(105, "Character", ItemClassification.progression),
    "Specter Knight":           SKPDItemData(106, "Character", ItemClassification.progression),
    "Plague Knight":            SKPDItemData(107, "Character", ItemClassification.progression),
    "Mole Knight":              SKPDItemData(108, "Character", ItemClassification.progression),
    "Treasure Knight":          SKPDItemData(109, "Character", ItemClassification.progression),
    "Tinker Knight":            SKPDItemData(110, "Character", ItemClassification.progression),
    "Polar Knight":             SKPDItemData(111, "Character", ItemClassification.progression),
    "Propeller Knight":         SKPDItemData(112, "Character", ItemClassification.progression),
    "Scrap Knight":             SKPDItemData(113, "Character", ItemClassification.progression),
    "Prism Knight":             SKPDItemData(114, "Character", ItemClassification.progression),
    "Puzzle Knight":            SKPDItemData(115, "Character", ItemClassification.progression),
    "Black Knight":             SKPDItemData(116, "Character", ItemClassification.progression),
    "Shield Knight":            SKPDItemData(117, "Character", ItemClassification.progression),
    "Mona":                     SKPDItemData(118, "Character", ItemClassification.progression),
    "Chester":                  SKPDItemData(119, "Character", ItemClassification.progression),
    "Enchantress":              SKPDItemData(120, "Character", ItemClassification.progression),
    "Quandary Sage":            SKPDItemData(121, "Character", ItemClassification.progression),
    "Spinwulf":                 SKPDItemData(122, "Character", ItemClassification.progression),
    "Schmutz":                  SKPDItemData(123, "Character", ItemClassification.progression),
    "Beefto":                   SKPDItemData(124, "Character", ItemClassification.progression),
    "Shuffle Knight":           SKPDItemData(125, "Character", ItemClassification.progression),
    "Random Knight":            SKPDItemData(126, "Character", ItemClassification.progression),

    "Meal Ticket":              SKPDItemData(127, "Relic", ItemClassification.progression, 1),
    "Premium Meal Ticket":      SKPDItemData(128, "Relic", ItemClassification.progression, 2),
    "Diamond Dust":             SKPDItemData(129, "Relic", ItemClassification.progression, 2),
    "Obsidian Drill":           SKPDItemData(130, "Relic", ItemClassification.useful, 0),
    "Snoutin' Charm":           SKPDItemData(131, "Relic", ItemClassification.useful, 0),
    "Shockproof Socks":         SKPDItemData(132, "Relic", ItemClassification.progression, 1),
    "Fizzle Wand":              SKPDItemData(133, "Relic", ItemClassification.useful, 0),
    "Bomb Seed Bag":            SKPDItemData(134, "Relic", ItemClassification.progression, 2),
    "Nimbus Balloon":           SKPDItemData(135, "Relic", ItemClassification.useful, 0),
    "Potion Napkin":            SKPDItemData(136, "Relic", ItemClassification.useful, 0),
    "Dynamallet":               SKPDItemData(137, "Relic", ItemClassification.useful, 0),
    "Power Pail":               SKPDItemData(138, "Relic", ItemClassification.progression, 1),
    "Desperation Talon":        SKPDItemData(139, "Relic", ItemClassification.useful, 0),
    "Gem Chain":                SKPDItemData(140, "Relic", ItemClassification.useful, 0),
    "Gem Beet":                 SKPDItemData(141, "Relic", ItemClassification.useful, 0),
    "Gold Leaf Clover":         SKPDItemData(142, "Relic", ItemClassification.useful, 0),
    "Swift Dagger":             SKPDItemData(143, "Relic", ItemClassification.progression, 3),
    "Third Amulet":             SKPDItemData(144, "Relic", ItemClassification.progression, 1),
    "Single Glove":             SKPDItemData(145, "Relic", ItemClassification.progression, 2),
    "Divine Liquid":            SKPDItemData(146, "Relic", ItemClassification.progression, 1),
    "Five String":              SKPDItemData(147, "Relic", ItemClassification.progression, 2),
    "Fenix Feather":            SKPDItemData(148, "Relic", ItemClassification.progression, 1),
    "Chronos Glass":            SKPDItemData(149, "Relic", ItemClassification.progression, 1),
    "Too Big Bomb":             SKPDItemData(150, "Relic", ItemClassification.progression, 1),
    "Toad Totem":               SKPDItemData(151, "Relic", ItemClassification.progression, 2),
    "Mentor Manual":            SKPDItemData(152, "Relic", ItemClassification.useful, 0),
    "Fury Horns":               SKPDItemData(153, "Relic", ItemClassification.progression, 1),
    "Zesty Slice":              SKPDItemData(154, "Relic", ItemClassification.progression, 1),
    "Chester's Chart":          SKPDItemData(155, "Relic", ItemClassification.useful, 0),
    "Super Skeleton Key":       SKPDItemData(156, "Relic", ItemClassification.useful, 0),
    "Ram Rod":                  SKPDItemData(157, "Relic", ItemClassification.progression, 1),
    "Conjuring Cupcake":        SKPDItemData(158, "Relic", ItemClassification.progression, 1),
    "Underdog Collar":          SKPDItemData(159, "Relic", ItemClassification.progression, 2),
    "Coin of Carnage":          SKPDItemData(160, "Relic", ItemClassification.progression, 1),
    "Coin of Cover":            SKPDItemData(161, "Relic", ItemClassification.progression, 1),
    "Bountiful Bugle":          SKPDItemData(162, "Relic", ItemClassification.useful, 0),
    "Time Capsule":             SKPDItemData(163, "Relic", ItemClassification.useful, 0),
    "Pocket Portal":            SKPDItemData(164, "Relic", ItemClassification.useful, 0),
    "Boomback Jar":             SKPDItemData(165, "Relic", ItemClassification.progression, 1),
    "Wicked Whetstone":         SKPDItemData(166, "Relic", ItemClassification.progression, 1),
    "Frosty Fauld":             SKPDItemData(167, "Relic", ItemClassification.progression, 2),
    "Thorny Tambourine":        SKPDItemData(168, "Relic", ItemClassification.progression, 2),
    "Hearty Wandy":             SKPDItemData(169, "Relic", ItemClassification.progression, 1),
    "Meal Coupon":              SKPDItemData(170, "Tief Relic", ItemClassification.useful),
    "Swift Stick":              SKPDItemData(171, "Tief Relic", ItemClassification.useful),
    "Toad Tadpole":             SKPDItemData(172, "Tief Relic", ItemClassification.useful),
    "Dubious Dust":             SKPDItemData(173, "Tief Relic", ItemClassification.useful),
    "Cheater Manual":           SKPDItemData(174, "Tief Relic", ItemClassification.useful),
    "Apple":                    SKPDItemData(175, "Tief Relic", ItemClassification.useful),
    "Cube of Lumbrix":          SKPDItemData(176, "Tief Relic", ItemClassification.useful),
    "Scholar's Sextant":        SKPDItemData(177, "Tief Relic", ItemClassification.useful),
    "Painter Kit":              SKPDItemData(178, "Tief Relic", ItemClassification.useful),
    "Portal Tracker":           SKPDItemData(179, "Tief Relic", ItemClassification.useful),

    "Almond":                   SKPDItemData(180, "Hat", ItemClassification.progression),
    "Souffle":                  SKPDItemData(181, "Hat", ItemClassification.progression),
    "Connoisseur's Cap":        SKPDItemData(182, "Hat", ItemClassification.filler),
    "Fleeto Beret":             SKPDItemData(183, "Hat", ItemClassification.filler),
    "Turkey Toque":             SKPDItemData(184, "Hat", ItemClassification.filler),
    "Taming Topper":            SKPDItemData(185, "Hat", ItemClassification.filler),
    "Scout's Cap":              SKPDItemData(186, "Hat", ItemClassification.filler),
    "Bohto Boater":             SKPDItemData(187, "Hat", ItemClassification.filler),
    "Present Hat":              SKPDItemData(188, "Hat", ItemClassification.filler),
    "Chest Lid":                SKPDItemData(189, "Hat", ItemClassification.filler),
    "Pauper's Cap":             SKPDItemData(190, "Hat", ItemClassification.filler),
    "Herder's Hat":             SKPDItemData(191, "Hat", ItemClassification.filler),
    "Platter Hatter":           SKPDItemData(192, "Hat", ItemClassification.filler),
    "Troupple Crown":           SKPDItemData(193, "Hat", ItemClassification.filler),
    "Mining Helmet":            SKPDItemData(194, "Hat", ItemClassification.filler),
    "Armorer's Bandana":        SKPDItemData(195, "Hat", ItemClassification.filler),
    "Volatile Heart Hat":       SKPDItemData(196, "Hat", ItemClassification.filler),
    "Summoning Slouch":         SKPDItemData(197, "Hat", ItemClassification.filler),
    "Bomb Bowler":              SKPDItemData(198, "Hat", ItemClassification.filler),
    "Dungstalker":              SKPDItemData(199, "Hat", ItemClassification.filler),
    "Spinwulf Snood":           SKPDItemData(200, "Hat", ItemClassification.filler),
    "No-Peek Nightcap":         SKPDItemData(201, "Hat", ItemClassification.filler),
    "Bugle Hat":                SKPDItemData(202, "Hat", ItemClassification.filler),
    "Extrovert Hat":            SKPDItemData(203, "Hat", ItemClassification.filler),
    "Monstruos Montera":        SKPDItemData(204, "Hat", ItemClassification.filler),
    "Meager Bowler":            SKPDItemData(205, "Hat", ItemClassification.filler),
    "Deflated Beret":           SKPDItemData(206, "Hat", ItemClassification.filler),
    "Extravagant Gem Hat":      SKPDItemData(207, "Hat", ItemClassification.filler),
    "Sluggish Beeto Beret":     SKPDItemData(208, "Hat", ItemClassification.filler),
    "Red Alert Beret":          SKPDItemData(209, "Hat", ItemClassification.filler),
    "Aqualorb Hat":             SKPDItemData(210, "Hat", ItemClassification.filler),
    "Rainbowlorb Hat":          SKPDItemData(211, "Hat", ItemClassification.filler),
    "Glitzem's Top Hat":        SKPDItemData(212, "Hat", ItemClassification.filler),
    "Floatsome Fez":            SKPDItemData(213, "Hat", ItemClassification.filler),
    "Birder Bicorne":           SKPDItemData(214, "Hat", ItemClassification.filler),
    "Hoppicles Helmet":         SKPDItemData(215, "Hat", ItemClassification.filler),
    "Goldarmor Crest":          SKPDItemData(216, "Hat", ItemClassification.filler),
    "Foegenerative Cap":        SKPDItemData(217, "Hat", ItemClassification.filler),
    "Swift Spinwulf Shapka":    SKPDItemData(218, "Hat", ItemClassification.filler),
    "Memmec's Kin Cap":         SKPDItemData(219, "Hat", ItemClassification.filler),
    "Growthclang Wig":          SKPDItemData(220, "Hat", ItemClassification.filler),
    "Honcho's Headdress":       SKPDItemData(221, "Hat", ItemClassification.filler),
    "Withering Turkey Skull":   SKPDItemData(222, "Hat", ItemClassification.filler),
    "Toque Blanche":            SKPDItemData(223, "Hat", ItemClassification.filler),
    "Shoddy Helmet":            SKPDItemData(224, "Hat", ItemClassification.filler),
    "Magnetic Morion":          SKPDItemData(225, "Hat", ItemClassification.filler),
    "Stonefall Ushanka":        SKPDItemData(226, "Hat", ItemClassification.filler),
    "Wall Hat":                 SKPDItemData(227, "Hat", ItemClassification.filler),
    "Half Top Hat":             SKPDItemData(228, "Hat", ItemClassification.filler),
    "Propeller Pith Helm":      SKPDItemData(229, "Hat", ItemClassification.filler),
    "Dash Slash Cap":           SKPDItemData(230, "Hat", ItemClassification.filler),
    "Stampede Stetson":         SKPDItemData(231, "Hat", ItemClassification.filler),
    "Stampede Stetson":         SKPDItemData(232, "Hat", ItemClassification.filler),
    "Bard's Waltzing Hat":      SKPDItemData(233, "Hat", ItemClassification.filler),
    "Transmuting Tammie":       SKPDItemData(234, "Hat", ItemClassification.filler),
    "Diluting Skullcap":        SKPDItemData(235, "Hat", ItemClassification.filler),
    "Upside-Crown":             SKPDItemData(236, "Hat", ItemClassification.filler),
    "Quester's Hat":            SKPDItemData(237, "Hat", ItemClassification.filler),
    "Cap of Plenty":            SKPDItemData(238, "Hat", ItemClassification.filler),
    "Picklehaube":              SKPDItemData(239, "Hat", ItemClassification.filler),
    "Protracted Beeto Beret":   SKPDItemData(240, "Hat", ItemClassification.filler),
    "Boneclang Skull":          SKPDItemData(241, "Hat", ItemClassification.filler),
    "Super Skeleton Skull":     SKPDItemData(242, "Hat", ItemClassification.filler),
    "Blorb Hat":                SKPDItemData(243, "Hat", ItemClassification.filler),
    "Lavalorb Hat":             SKPDItemData(244, "Hat", ItemClassification.filler),
    "Freezorb Hat":             SKPDItemData(245, "Hat", ItemClassification.filler),
    "Needleorb Hat":            SKPDItemData(246, "Hat", ItemClassification.filler),
    "Conveyorb Hat":            SKPDItemData(247, "Hat", ItemClassification.filler),
    "Wizzem Hat":               SKPDItemData(248, "Hat", ItemClassification.filler),
    "Legendary Foe Helm":       SKPDItemData(249, "Hat", ItemClassification.filler),
    "Legendary Hazard Helm":    SKPDItemData(250, "Hat", ItemClassification.filler),
    "Invisishade Cap":          SKPDItemData(251, "Hat", ItemClassification.filler),
    "Moler Hat":                SKPDItemData(252, "Hat", ItemClassification.filler),
    "Gremlin's Cap":            SKPDItemData(253, "Hat", ItemClassification.filler),
    "Hazardous Headgear":       SKPDItemData(254, "Hat", ItemClassification.filler),
    "Terrorpin's Toque":        SKPDItemData(255, "Hat", ItemClassification.filler),
    "Snow Pelt Cap":            SKPDItemData(256, "Hat", ItemClassification.filler),
    "Troupple Acolyte's Hat":   SKPDItemData(257, "Hat", ItemClassification.filler),
    "Myopic Top Hat":           SKPDItemData(258, "Hat", ItemClassification.filler),
    "Darkness Veil":            SKPDItemData(259, "Hat", ItemClassification.filler),
    "Jack-o'-Hattern":          SKPDItemData(260, "Hat", ItemClassification.filler),
    "Toad Totem Topper":        SKPDItemData(261, "Hat", ItemClassification.filler),
    "Toxic Turban":             SKPDItemData(262, "Hat", ItemClassification.filler),
    "Goo Bumpin' Bonnet":       SKPDItemData(263, "Hat", ItemClassification.filler),
    "Cauldron Cap":             SKPDItemData(264, "Hat", ItemClassification.filler),
    "Haste Helm":               SKPDItemData(265, "Hat", ItemClassification.filler),
    "Juggler's Cap":            SKPDItemData(266, "Hat", ItemClassification.filler),
    "Wrathful Tyrolean":        SKPDItemData(267, "Hat", ItemClassification.filler),
    "Inverted Chest Hat":       SKPDItemData(268, "Hat", ItemClassification.filler),
    "Teleporter's Trapper":     SKPDItemData(269, "Hat", ItemClassification.filler),
    "Legendary Gold Helm":      SKPDItemData(270, "Hat", ItemClassification.filler),
    "Shuffler's Hat":           SKPDItemData(271, "Hat", ItemClassification.filler),

    "Helm of Shovelry":         SKPDItemData(272, "Hat", ItemClassification.filler),
    "Helm of Fortune":          SKPDItemData(273, "Hat", ItemClassification.filler),
    "Helm of Toil":             SKPDItemData(274, "Hat", ItemClassification.filler),
    "Helm of Protection":       SKPDItemData(275, "Hat", ItemClassification.filler),
    "Helm of Royalty":          SKPDItemData(276, "Hat", ItemClassification.filler),
    "Helm of Torment":          SKPDItemData(278, "Hat", ItemClassification.filler),
    "Helm of Alchemy":          SKPDItemData(279, "Hat", ItemClassification.filler),
    "Helm of Invention":        SKPDItemData(280, "Hat", ItemClassification.filler),
    "Helm of Fancy":            SKPDItemData(281, "Hat", ItemClassification.filler),
    "Helm of Power":            SKPDItemData(282, "Hat", ItemClassification.filler),
    "Helm of Vigilance":        SKPDItemData(283, "Hat", ItemClassification.filler),
    "Helm of Hoarding":         SKPDItemData(284, "Hat", ItemClassification.filler),
    "Helm of Refraction":       SKPDItemData(285, "Hat", ItemClassification.filler),
    "Helm of Analysis":         SKPDItemData(286, "Hat", ItemClassification.filler),
    "Helm of Research":         SKPDItemData(287, "Hat", ItemClassification.filler),
    "Helm of Adaptation":       SKPDItemData(288, "Hat", ItemClassification.filler),
    "Entrepreneurs' Lid":       SKPDItemData(289, "Hat", ItemClassification.filler),
    "Skullcap of Fate":         SKPDItemData(290, "Hat", ItemClassification.filler),

    "Junk":                     SKPDItemData(291, "Filler", ItemClassification.trap),
    "Gems":                     SKPDItemData(292, "Filler", ItemClassification.filler)
}