from BaseClasses import Item, ItemClassification
from typing import NamedTuple

class PocketDungeonItem(Item):
    game: str = "Shovel Knight Pocket Dungeon"

class PocketDungeonItemData(NamedTuple):
    index: int
    category: str
    classification: ItemClassification

itemtable: dict[str, PocketDungeonItemData] = {
    "Shop Restock":             PocketDungeonItemData(112, "Progression", ItemClassification.progression),
    "Key Piece":                PocketDungeonItemData(112, "Progression", ItemClassification.progression),
    "Progressive Dungeon":      PocketDungeonItemData(112, "Progression", ItemClassification.progression),

    "Plains of Passage":        PocketDungeonItemData(101, "Dungeon", ItemClassification.progression),
    "Pridemoor Keep":           PocketDungeonItemData(102, "Dungeon", ItemClassification.progression),
    "Lich Yard":                PocketDungeonItemData(103, "Dungeon", ItemClassification.progression),
    "Explodatorium":            PocketDungeonItemData(104, "Dungeon", ItemClassification.progression),
    "Magic Landfill":           PocketDungeonItemData(105, "Dungeon", ItemClassification.progression),
    "Iron Whale":               PocketDungeonItemData(106, "Dungeon", ItemClassification.progression),
    "Lost City":                PocketDungeonItemData(107, "Dungeon", ItemClassification.progression),
    "Chromatic Caverns":        PocketDungeonItemData(108, "Dungeon", ItemClassification.progression),
    "Clockwork Tower":          PocketDungeonItemData(109, "Dungeon", ItemClassification.progression),
    "Stranded Ship":            PocketDungeonItemData(110, "Dungeon", ItemClassification.progression),
    "Flying Machine":           PocketDungeonItemData(111, "Dungeon", ItemClassification.progression),
    #just in case you can replace the final levels again
    #"Scholar Sanctum":          PocketDungeonItemData(110, "Dungeon", ItemClassification.progression), 
    #"Tower of Fate":            PocketDungeonItemData(111, "Dungeon", ItemClassification.progression),

    "Shovel Knight":            PocketDungeonItemData(112, "Character", ItemClassification.progression),
    "King Knight":              PocketDungeonItemData(113, "Character", ItemClassification.progression),
    "Specter Knight":           PocketDungeonItemData(114, "Character", ItemClassification.progression),
    "Plague Knight":            PocketDungeonItemData(115, "Character", ItemClassification.progression),
    "Mole Knight":              PocketDungeonItemData(116, "Character", ItemClassification.progression),
    "Treasure Knight":          PocketDungeonItemData(117, "Character", ItemClassification.progression),
    "Tinker Knight":            PocketDungeonItemData(118, "Character", ItemClassification.progression),
    "Polar Knight":             PocketDungeonItemData(119, "Character", ItemClassification.progression),
    "Propeller Knight":         PocketDungeonItemData(120, "Character", ItemClassification.progression),
    "Scrap Knight":             PocketDungeonItemData(121, "Character", ItemClassification.progression),
    "Prism Knight":             PocketDungeonItemData(122, "Character", ItemClassification.progression),
    "Puzzle Knight":            PocketDungeonItemData(123, "Character", ItemClassification.progression),
    "Black Knight":             PocketDungeonItemData(124, "Character", ItemClassification.progression),
    "Shield Knight":            PocketDungeonItemData(125, "Character", ItemClassification.progression),
    "Mona":                     PocketDungeonItemData(126, "Character", ItemClassification.progression),
    "Chester":                  PocketDungeonItemData(126, "Character", ItemClassification.progression),
    "Enchantress":              PocketDungeonItemData(126, "Character", ItemClassification.progression),
    "Quandary Sage":            PocketDungeonItemData(127, "Bonus Character", ItemClassification.progression),
    "Spinwulf":                 PocketDungeonItemData(128, "Bonus Character", ItemClassification.progression),
    "Schmutz":                  PocketDungeonItemData(129, "Bonus Character", ItemClassification.progression),
    "Beefto":                   PocketDungeonItemData(130, "Bonus Character", ItemClassification.progression),
    "Shuffle Knight":           PocketDungeonItemData(129, "Bonus Character", ItemClassification.progression),
    "Random Knight":            PocketDungeonItemData(130, "Bonus Character", ItemClassification.progression),

    "Meal Ticket":              PocketDungeonItemData(131, "Relic", ItemClassification.useful),
    "Premium Meal Ticket":      PocketDungeonItemData(132, "Relic", ItemClassification.useful),
    "Diamond Dust":             PocketDungeonItemData(133, "Relic", ItemClassification.useful),
    "Obsidian Drill":           PocketDungeonItemData(134, "Relic", ItemClassification.useful),
    "Snoutin' Charm":           PocketDungeonItemData(135, "Relic", ItemClassification.useful),
    "Shockproof Socks":         PocketDungeonItemData(136, "Relic", ItemClassification.useful),
    "Fizzle Wand":              PocketDungeonItemData(137, "Relic", ItemClassification.useful),
    "Bomb Seed Bag":            PocketDungeonItemData(138, "Relic", ItemClassification.useful),
    "Nimbus Balloon":           PocketDungeonItemData(139, "Relic", ItemClassification.useful),
    "Potion Napkin":            PocketDungeonItemData(140, "Relic", ItemClassification.useful),
    "Dynamallet":               PocketDungeonItemData(141, "Relic", ItemClassification.useful),
    "Power Pail":               PocketDungeonItemData(142, "Relic", ItemClassification.useful),
    "Desperation Talon":        PocketDungeonItemData(143, "Relic", ItemClassification.useful),
    "Gem Chain":                PocketDungeonItemData(144, "Relic", ItemClassification.useful),
    "Gem Beet":                 PocketDungeonItemData(145, "Relic", ItemClassification.useful),
    "Gold Leaf Clover":         PocketDungeonItemData(146, "Relic", ItemClassification.useful),
    "Swift Dagger":             PocketDungeonItemData(147, "Relic", ItemClassification.useful),
    "Third Amulet":             PocketDungeonItemData(148, "Relic", ItemClassification.useful),
    "Single Glove":             PocketDungeonItemData(149, "Relic", ItemClassification.useful),
    "Divine Liquid":            PocketDungeonItemData(150, "Relic", ItemClassification.useful),
    "Five String":              PocketDungeonItemData(151, "Relic", ItemClassification.useful),
    "Fenix Feather":            PocketDungeonItemData(152, "Relic", ItemClassification.useful),
    "Chronos Glass":            PocketDungeonItemData(153, "Relic", ItemClassification.useful),
    "Too Big Bomb":             PocketDungeonItemData(154, "Relic", ItemClassification.useful),
    "Toad Totem":               PocketDungeonItemData(155, "Relic", ItemClassification.useful),
    "Mentor Manual":            PocketDungeonItemData(156, "Relic", ItemClassification.useful),
    "Fury Horns":               PocketDungeonItemData(157, "Relic", ItemClassification.useful),
    "Zesty Slice":              PocketDungeonItemData(158, "Relic", ItemClassification.useful),
    "Chester's Chart":          PocketDungeonItemData(159, "Relic", ItemClassification.useful),
    "Super Skeleton Key":       PocketDungeonItemData(160, "Relic", ItemClassification.useful),
    "Ram Rod":                  PocketDungeonItemData(161, "Relic", ItemClassification.useful),
    "Conjuring Cupcake":        PocketDungeonItemData(162, "Relic", ItemClassification.useful),
    "Underdog Collar":          PocketDungeonItemData(163, "Relic", ItemClassification.useful),
    "Coin of Carnage":          PocketDungeonItemData(164, "Relic", ItemClassification.useful),
    "Coin of Cover":            PocketDungeonItemData(165, "Relic", ItemClassification.useful),
    "Bountiful Bugle":          PocketDungeonItemData(166, "Relic", ItemClassification.useful),
    "Time Capsule":             PocketDungeonItemData(167, "Relic", ItemClassification.useful),
    "Pocket Portal":            PocketDungeonItemData(168, "Relic", ItemClassification.useful),
    "Boomback Jar":             PocketDungeonItemData(169, "Relic", ItemClassification.useful),
    "Wicked Whetstone":         PocketDungeonItemData(170, "Relic", ItemClassification.useful),
    "Frosty Fauld":             PocketDungeonItemData(171, "Relic", ItemClassification.useful),
    "Thorny Tambourine":        PocketDungeonItemData(172, "Relic", ItemClassification.useful),
    "Hearty Wandy":             PocketDungeonItemData(173, "Relic", ItemClassification.useful),
    "Meal Coupon":              PocketDungeonItemData(174, "Tief Relic", ItemClassification.useful),
    "Swift Stick":              PocketDungeonItemData(175, "Tief Relic", ItemClassification.useful),
    "Toad Tadpole":             PocketDungeonItemData(176, "Tief Relic", ItemClassification.useful),
    "Dubious Dust":             PocketDungeonItemData(177, "Tief Relic", ItemClassification.useful),
    "Cheater Manual":           PocketDungeonItemData(178, "Tief Relic", ItemClassification.useful),
    "Apple":                    PocketDungeonItemData(179, "Tief Relic", ItemClassification.useful),
    "Cube of Lumbrix":          PocketDungeonItemData(180, "Tief Relic", ItemClassification.useful),
    "Scholar's Sextant":        PocketDungeonItemData(181, "Tief Relic", ItemClassification.useful),
    "Painter Kit":              PocketDungeonItemData(182, "Tief Relic", ItemClassification.useful),
    "Portal Tracker":           PocketDungeonItemData(183, "Tief Relic", ItemClassification.useful),

    "Connoisseur's Cap":        PocketDungeonItemData(184, "Hat", ItemClassification.filler),
    "Fleeto Beret":             PocketDungeonItemData(184, "Hat", ItemClassification.filler),
    "Turkey Toque":             PocketDungeonItemData(184, "Hat", ItemClassification.filler),
    "Taming Topper":            PocketDungeonItemData(184, "Hat", ItemClassification.filler),
    "Scout's Cap":              PocketDungeonItemData(184, "Hat", ItemClassification.filler),
    "Bohto Boater":             PocketDungeonItemData(184, "Hat", ItemClassification.filler),
    "Present Hat":              PocketDungeonItemData(184, "Hat", ItemClassification.filler),
    "Chest Lid":                PocketDungeonItemData(184, "Hat", ItemClassification.filler),
    "Pauper's Cap":             PocketDungeonItemData(184, "Hat", ItemClassification.filler),
    "Herder's Hat":             PocketDungeonItemData(184, "Hat", ItemClassification.filler),
    "Platter Hatter":           PocketDungeonItemData(184, "Hat", ItemClassification.filler),
    "Troupple Crown":           PocketDungeonItemData(184, "Hat", ItemClassification.filler),
    "Mining Helmet":            PocketDungeonItemData(184, "Hat", ItemClassification.filler),
    "Armorer's Bandana":        PocketDungeonItemData(184, "Hat", ItemClassification.filler),
    "Volatile Heart Hat":       PocketDungeonItemData(184, "Hat", ItemClassification.filler),
    "Summoning Slouch":         PocketDungeonItemData(184, "Hat", ItemClassification.filler),
    "Bomb Bowler":              PocketDungeonItemData(184, "Hat", ItemClassification.filler),
    "Dungstalker":              PocketDungeonItemData(184, "Hat", ItemClassification.filler),
    "Spinwulf Snood":           PocketDungeonItemData(184, "Hat", ItemClassification.filler),
    "No-Peek Nightcap":         PocketDungeonItemData(184, "Hat", ItemClassification.filler),
    "Bugle Hat":                PocketDungeonItemData(184, "Hat", ItemClassification.filler),
    "Extrovert Hat":            PocketDungeonItemData(184, "Hat", ItemClassification.filler),
    "Almond":                   PocketDungeonItemData(184, "Hat", ItemClassification.filler),
    "Souffle":                  PocketDungeonItemData(184, "Hat", ItemClassification.filler),
    "Monstruos Montera":        PocketDungeonItemData(184, "Hat", ItemClassification.filler),
    "Meager Bowler":            PocketDungeonItemData(184, "Hat", ItemClassification.filler),
    "Deflated Beret":           PocketDungeonItemData(184, "Hat", ItemClassification.filler),
    "Extravagant Gem Hat":      PocketDungeonItemData(184, "Hat", ItemClassification.filler),
    "Sluggish Beeto Beret":     PocketDungeonItemData(184, "Hat", ItemClassification.filler),
    "Red Alert Beret":          PocketDungeonItemData(184, "Hat", ItemClassification.filler),
    "Aqualorb Hat":             PocketDungeonItemData(184, "Hat", ItemClassification.filler),
    "Rainbowlorb Hat":          PocketDungeonItemData(184, "Hat", ItemClassification.filler),
    "Glitzem's Top Hat":        PocketDungeonItemData(184, "Hat", ItemClassification.filler),
    "Floatsome Fez":            PocketDungeonItemData(184, "Hat", ItemClassification.filler),
    "Birder Bicorne":           PocketDungeonItemData(184, "Hat", ItemClassification.filler),
    "Hoppicles Helmet":         PocketDungeonItemData(184, "Hat", ItemClassification.filler),
    "Goldarmor Crest":          PocketDungeonItemData(184, "Hat", ItemClassification.filler),
    "Foegenerative Cap":        PocketDungeonItemData(184, "Hat", ItemClassification.filler),
    "Swift Spinwulf Shapka":    PocketDungeonItemData(184, "Hat", ItemClassification.filler),
    "Memmec's Kin Cap":         PocketDungeonItemData(184, "Hat", ItemClassification.filler),
    "Growthclang Wig":          PocketDungeonItemData(184, "Hat", ItemClassification.filler),
    "Honcho's Headdress":       PocketDungeonItemData(184, "Hat", ItemClassification.filler),
    "Withering Turkey Skull":   PocketDungeonItemData(184, "Hat", ItemClassification.filler),
    "Toque Blanche":            PocketDungeonItemData(184, "Hat", ItemClassification.filler),
    "Shoddy Helmet":            PocketDungeonItemData(184, "Hat", ItemClassification.filler),
    "Magnetic Morion":          PocketDungeonItemData(184, "Hat", ItemClassification.filler),
    "Stonefall Ushanka":        PocketDungeonItemData(184, "Hat", ItemClassification.filler),
    "Wall Hat":                 PocketDungeonItemData(184, "Hat", ItemClassification.filler),
    "Half Top Hat":             PocketDungeonItemData(184, "Hat", ItemClassification.filler),
    "Propeller Pith Helm":      PocketDungeonItemData(184, "Hat", ItemClassification.filler),
    "Dash Slash Cap":           PocketDungeonItemData(184, "Hat", ItemClassification.filler),
    "Stampede Stetson":         PocketDungeonItemData(184, "Hat", ItemClassification.filler),
    "Bard's Waltzing Hat":      PocketDungeonItemData(184, "Hat", ItemClassification.filler),
    "Transmuting Tammie":       PocketDungeonItemData(184, "Hat", ItemClassification.filler),
    "Diluting Skullcap":        PocketDungeonItemData(184, "Hat", ItemClassification.filler),
    "Upside-Crown":             PocketDungeonItemData(184, "Hat", ItemClassification.filler),
    "Quester's Hat":            PocketDungeonItemData(184, "Hat", ItemClassification.filler),
    "Cap of Plenty":            PocketDungeonItemData(184, "Hat", ItemClassification.filler),
    "Picklehaube":              PocketDungeonItemData(184, "Hat", ItemClassification.filler),
    "Protracted Beeto Beret":   PocketDungeonItemData(184, "Hat", ItemClassification.filler),
    "Boneclang Skull":          PocketDungeonItemData(184, "Hat", ItemClassification.filler),
    "Super Skeleton Skull":     PocketDungeonItemData(184, "Hat", ItemClassification.filler),
    "Blorb Hat":                PocketDungeonItemData(184, "Hat", ItemClassification.filler),
    "Lavalorb Hat":             PocketDungeonItemData(184, "Hat", ItemClassification.filler),
    "Freezorb Hat":             PocketDungeonItemData(184, "Hat", ItemClassification.filler),
    "Needleorb Hat":            PocketDungeonItemData(184, "Hat", ItemClassification.filler),
    "Conveyorb Hat":            PocketDungeonItemData(184, "Hat", ItemClassification.filler),
    "Wizzem Hat":               PocketDungeonItemData(184, "Hat", ItemClassification.filler),
    "Legendary Foe Helm":       PocketDungeonItemData(184, "Hat", ItemClassification.filler),
    "Legendary Hazard Helm":    PocketDungeonItemData(184, "Hat", ItemClassification.filler),
    "Invisishade Cap":          PocketDungeonItemData(184, "Hat", ItemClassification.filler),
    "Moler Hat":                PocketDungeonItemData(184, "Hat", ItemClassification.filler),
    "Gremlin's Cap":            PocketDungeonItemData(184, "Hat", ItemClassification.filler),
    "Hazardous Headgear":       PocketDungeonItemData(184, "Hat", ItemClassification.filler),
    "Terrorpin's Toque":        PocketDungeonItemData(184, "Hat", ItemClassification.filler),
    "Snow Pelt Cap":            PocketDungeonItemData(184, "Hat", ItemClassification.filler),
    "Troupple Acolyte's Hat":   PocketDungeonItemData(184, "Hat", ItemClassification.filler),
    "Myopic Top Hat":           PocketDungeonItemData(184, "Hat", ItemClassification.filler),
    "Darkness Veil":            PocketDungeonItemData(184, "Hat", ItemClassification.filler),
    "Jack-o'-Hattern":          PocketDungeonItemData(184, "Hat", ItemClassification.filler),
    "Toad Totem Topper":        PocketDungeonItemData(184, "Hat", ItemClassification.filler),
    "Toxic Turban":             PocketDungeonItemData(184, "Hat", ItemClassification.filler),
    "Goo Bumpin' Bonnet":       PocketDungeonItemData(184, "Hat", ItemClassification.filler),
    "Cauldron Cap":             PocketDungeonItemData(184, "Hat", ItemClassification.filler),
    "Haste Helm":               PocketDungeonItemData(184, "Hat", ItemClassification.filler),
    "Juggler's Cap":            PocketDungeonItemData(184, "Hat", ItemClassification.filler),
    "Wrathful Tyrolean":        PocketDungeonItemData(184, "Hat", ItemClassification.filler),
    "Inverted Chest Hat":       PocketDungeonItemData(184, "Hat", ItemClassification.filler),
    "Teleporter's Trapper":     PocketDungeonItemData(184, "Hat", ItemClassification.filler),
    "Legendary Gold Helm":      PocketDungeonItemData(184, "Hat", ItemClassification.filler),
    "Shuffler's Hat":           PocketDungeonItemData(184, "Hat", ItemClassification.filler),

    "Helm of Shovelry":         PocketDungeonItemData(184, "Helm", ItemClassification.filler),
    "Helm of Fortune":          PocketDungeonItemData(184, "Helm", ItemClassification.filler),
    "Helm of Toil":             PocketDungeonItemData(184, "Helm", ItemClassification.filler),
    "Helm of Protection":       PocketDungeonItemData(184, "Helm", ItemClassification.filler),
    "Helm of Royalty":          PocketDungeonItemData(184, "Helm", ItemClassification.filler),
    "Helm of Torment":          PocketDungeonItemData(184, "Helm", ItemClassification.filler),
    "Helm of Alchemy":          PocketDungeonItemData(184, "Helm", ItemClassification.filler),
    "Helm of Invention":        PocketDungeonItemData(184, "Helm", ItemClassification.filler),
    "Helm of Fancy":            PocketDungeonItemData(184, "Helm", ItemClassification.filler),
    "Helm of Power":            PocketDungeonItemData(184, "Helm", ItemClassification.filler),
    "Helm of Vigilance":        PocketDungeonItemData(184, "Helm", ItemClassification.filler),
    "Helm of Hoarding":         PocketDungeonItemData(184, "Helm", ItemClassification.filler),
    "Helm of Refraction":       PocketDungeonItemData(184, "Helm", ItemClassification.filler),
    "Helm of Analysis":         PocketDungeonItemData(184, "Helm", ItemClassification.filler),
    "Helm of Research":         PocketDungeonItemData(184, "Helm", ItemClassification.filler),
    "Helm of Adaptation":       PocketDungeonItemData(184, "Helm", ItemClassification.filler),
    "Entrepreneurs' Lid":       PocketDungeonItemData(184, "Helm", ItemClassification.filler),
    "Skullcap of Fate":         PocketDungeonItemData(184, "Helm", ItemClassification.filler),
}