from BaseClasses import Item, ItemClassification
from typing import NamedTuple, Any

class SKPDItem(Item):
    game: str = "Shovel Knight Pocket Dungeon"

class SKPDItemData(NamedTuple):
    code: int
    category: str
    classification: ItemClassification
    data: Any = None

def get_item_from_category(category: str) -> list[str]:
    itemlist = []
    for item in skpd_items:
        if skpd_items[item].category == category:
            itemlist.append(item)
    return itemlist

skpd_items: dict[str, SKPDItemData] = {
    "Shop Restock":             SKPDItemData(101, "Progression", ItemClassification.progression),
    "Key Fragment":             SKPDItemData(102, "Progression", ItemClassification.progression),
    "Progressive Dungeon":      SKPDItemData(103, "Progression", ItemClassification.progression),
    "Key":                      SKPDItemData(293, "Progression", ItemClassification.progression),
    "Garbage":                  SKPDItemData(291, "Filler", ItemClassification.trap),
    "1000 Gems":                SKPDItemData(292, "Filler", ItemClassification.filler),
    "2500 Gems":                SKPDItemData(294, "Filler", ItemClassification.filler),
    "5000 Gems":                SKPDItemData(295, "Filler", ItemClassification.filler),

    "Shovel Knight":            SKPDItemData(104, "Character", ItemClassification.progression),
    "King Knight":              SKPDItemData(105, "Character", ItemClassification.progression),
    "Specter Knight":           SKPDItemData(106, "Character", ItemClassification.progression),
    "Plague Knight":            SKPDItemData(107, "Character", ItemClassification.progression),
    "Mole Knight":              SKPDItemData(108, "Character", ItemClassification.progression),
    "Treasure Knight":          SKPDItemData(109, "Character", ItemClassification.progression),
    "Tinker Knight":            SKPDItemData(110, "Character", ItemClassification.progression),
    "Polar Knight":             SKPDItemData(111, "Character", ItemClassification.progression),
    "Propeller Knight":         SKPDItemData(112, "Character", ItemClassification.progression),
    "Scrap Knight":             SKPDItemData(113, "Character", ItemClassification.progression),
    "Prism Knight":             SKPDItemData(114, "Character", ItemClassification.progression),
    "Puzzle Knight":            SKPDItemData(115, "Character", ItemClassification.progression),
    "Black Knight":             SKPDItemData(116, "Character", ItemClassification.progression),
    "Shield Knight":            SKPDItemData(117, "Character", ItemClassification.progression),
    "Mona":                     SKPDItemData(118, "Character", ItemClassification.progression),
    "Chester":                  SKPDItemData(119, "Character", ItemClassification.progression),
    "Enchantress":              SKPDItemData(120, "Character", ItemClassification.progression),
    "Quandary Sage":            SKPDItemData(121, "Character", ItemClassification.useful),
    "Spinwulf":                 SKPDItemData(122, "Character", ItemClassification.progression),
    "Schmutz":                  SKPDItemData(123, "Character", ItemClassification.progression),
    "Beefto":                   SKPDItemData(124, "Character", ItemClassification.progression),
    # "Shuffle Knight":           SKPDItemData(125, "Character", ItemClassification.progression),
    # "Random Knight":            SKPDItemData(126, "Character", ItemClassification.progression),

    "Shovel Knight B":          SKPDItemData(350, "Refract Character", ItemClassification.progression),
    "King Knight B":            SKPDItemData(351, "Refract Character", ItemClassification.progression),
    "Specter Knight B":         SKPDItemData(352, "Refract Character", ItemClassification.progression),
    "Plague Knight B":          SKPDItemData(353, "Refract Character", ItemClassification.progression),
    "Mole Knight B":            SKPDItemData(354, "Refract Character", ItemClassification.progression),
    "Treasure Knight B":        SKPDItemData(355, "Refract Character", ItemClassification.progression),
    "Tinker Knight B":          SKPDItemData(356, "Refract Character", ItemClassification.progression),
    "Polar Knight B":           SKPDItemData(357, "Refract Character", ItemClassification.progression),
    "Propeller Knight B":       SKPDItemData(358, "Refract Character", ItemClassification.progression),
    "Scrap Knight B":           SKPDItemData(359, "Refract Character", ItemClassification.progression),
    "Prism Knight B":           SKPDItemData(360, "Refract Character", ItemClassification.progression),
    "Puzzle Knight B":          SKPDItemData(361, "Refract Character", ItemClassification.progression),
    "Black Knight B":           SKPDItemData(362, "Refract Character", ItemClassification.progression),
    "Shield Knight B":          SKPDItemData(363, "Refract Character", ItemClassification.progression),
    "Mona B":                   SKPDItemData(364, "Refract Character", ItemClassification.progression),
    "Chester B":                SKPDItemData(365, "Refract Character", ItemClassification.progression),
    "Enchantress B":            SKPDItemData(366, "Refract Character", ItemClassification.progression),
    # "Shuffle Knight B":         SKPDItemData(367, "Refract Character", ItemClassification.progression),

    "Meal Ticket":              SKPDItemData(127, "Relic", ItemClassification.progression, 1),
    "Premium Meal Ticket":      SKPDItemData(128, "Relic", ItemClassification.progression, 2),
    "Diamond Dust":             SKPDItemData(129, "Relic", ItemClassification.progression, 2),
    "Obsidian Drill":           SKPDItemData(130, "Relic", ItemClassification.useful, 0),
    "Snoutin' Charm":           SKPDItemData(131, "Relic", ItemClassification.useful, 0),
    "Shockproof Socks":         SKPDItemData(132, "Relic", ItemClassification.progression, 1),
    "Fizzle Wand":              SKPDItemData(133, "Relic", ItemClassification.useful, 0),
    "Bomb Seed Bag":            SKPDItemData(134, "Relic", ItemClassification.progression, 2),
    "Nimbus Balloon":           SKPDItemData(135, "Relic", ItemClassification.useful, 0),
    "Potion Napkin":            SKPDItemData(136, "Relic", ItemClassification.filler, 0),
    "Dynamallet":               SKPDItemData(137, "Relic", ItemClassification.useful, 0),
    "Power Pail":               SKPDItemData(138, "Relic", ItemClassification.progression, 1),
    "Desperation Talon":        SKPDItemData(139, "Relic", ItemClassification.useful, 0),
    "Gem Chain":                SKPDItemData(140, "Relic", ItemClassification.useful, 0),
    "Gem Beet":                 SKPDItemData(141, "Relic", ItemClassification.useful, 0),
    "Gold Leaf Clover":         SKPDItemData(142, "Relic", ItemClassification.useful, 0),
    "Swift Dagger":             SKPDItemData(143, "Relic", ItemClassification.progression, 3),
    "Third Amulet":             SKPDItemData(144, "Relic", ItemClassification.progression, 1),
    "Single Glove":             SKPDItemData(145, "Relic", ItemClassification.progression, 2),
    "Divine Liquid":            SKPDItemData(146, "Relic", ItemClassification.progression, 1),
    "Five String":              SKPDItemData(147, "Relic", ItemClassification.progression, 2),
    "Fenix Feather":            SKPDItemData(148, "Relic", ItemClassification.progression, 1),
    "Chronos Glass":            SKPDItemData(149, "Relic", ItemClassification.progression, 1),
    "Too Big Bomb":             SKPDItemData(150, "Relic", ItemClassification.progression, 1),
    "Toad Totem":               SKPDItemData(151, "Relic", ItemClassification.progression, 2),
    "Mentor Manual":            SKPDItemData(152, "Relic", ItemClassification.useful, 0),
    "Fury Horns":               SKPDItemData(153, "Relic", ItemClassification.progression, 1),
    "Zesty Slice":              SKPDItemData(154, "Relic", ItemClassification.progression, 1),
    "Chester's Chart":          SKPDItemData(155, "Relic", ItemClassification.useful, 0),
    "Super Skeleton Key":       SKPDItemData(156, "Relic", ItemClassification.useful, 0),
    "Ram Rod":                  SKPDItemData(157, "Relic", ItemClassification.progression, 1),
    "Conjuring Cupcake":        SKPDItemData(158, "Relic", ItemClassification.progression, 1),
    "Underdog Collar":          SKPDItemData(159, "Relic", ItemClassification.progression, 2),
    "Coin of Carnage":          SKPDItemData(160, "Relic", ItemClassification.progression, 1),
    "Coin of Cover":            SKPDItemData(161, "Relic", ItemClassification.progression, 1),
    "Bountiful Bugle":          SKPDItemData(162, "Relic", ItemClassification.useful, 0),
    "Time Capsule":             SKPDItemData(163, "Relic", ItemClassification.useful, 0),
    "Pocket Portal":            SKPDItemData(164, "Relic", ItemClassification.useful, 0),
    "Boomback Jar":             SKPDItemData(165, "Relic", ItemClassification.progression, 1),
    "Wicked Whetstone":         SKPDItemData(166, "Relic", ItemClassification.progression, 1),
    "Frosty Fauld":             SKPDItemData(167, "Relic", ItemClassification.progression, 2),
    "Thorny Tambourine":        SKPDItemData(168, "Relic", ItemClassification.progression, 2),
    "Hearty Wandy":             SKPDItemData(169, "Relic", ItemClassification.progression, 1),
    "Meal Coupon":              SKPDItemData(170, "Tief Relic", ItemClassification.useful),
    "Swift Stick":              SKPDItemData(171, "Tief Relic", ItemClassification.useful),
    "Toad Tadpole":             SKPDItemData(172, "Tief Relic", ItemClassification.useful),
    "Dubious Dust":             SKPDItemData(173, "Tief Relic", ItemClassification.useful),
    "Cheater Manual":           SKPDItemData(174, "Tief Relic", ItemClassification.useful),
    "Apple":                    SKPDItemData(175, "Tief Relic", ItemClassification.useful),
    "Cube of Lumbrix":          SKPDItemData(176, "Tief Relic", ItemClassification.useful),
    "Scholar's Sextant":        SKPDItemData(177, "Tief Relic", ItemClassification.useful),
    "Painter Kit":              SKPDItemData(178, "Tief Relic", ItemClassification.useful),
    "Portal Tracker":           SKPDItemData(179, "Tief Relic", ItemClassification.useful),

    #"Almond":                   SKPDItemData(180, "Hat", ItemClassification.progression),
    #"Souffle":                  SKPDItemData(181, "Hat", ItemClassification.progression),
    "Connoisseur's Cap":        SKPDItemData(182, "Hat", ItemClassification.filler),
    "Fleeto Beret":             SKPDItemData(183, "Hat", ItemClassification.filler),
    "Turkey Toque":             SKPDItemData(184, "Hat", ItemClassification.filler),
    "Taming Topper":            SKPDItemData(185, "Hat", ItemClassification.filler),
    "Scout's Cap":              SKPDItemData(186, "Hat", ItemClassification.filler),
    "Bohto Boater":             SKPDItemData(187, "Hat", ItemClassification.filler),
    "Present Hat":              SKPDItemData(188, "Hat", ItemClassification.filler),
    "Chest Lid":                SKPDItemData(189, "Hat", ItemClassification.trap),
    "Pauper's Cap":             SKPDItemData(190, "Hat", ItemClassification.trap),
    "Herder's Hat":             SKPDItemData(191, "Hat", ItemClassification.trap),
    "Platter Hatter":           SKPDItemData(192, "Hat", ItemClassification.filler),
    "Troupple Crown":           SKPDItemData(193, "Hat", ItemClassification.filler),
    "Mining Helmet":            SKPDItemData(194, "Hat", ItemClassification.trap),
    "Armorer's Bandana":        SKPDItemData(195, "Hat", ItemClassification.filler),
    "Volatile Heart Hat":       SKPDItemData(196, "Hat", ItemClassification.trap),
    "Summoning Slouch":         SKPDItemData(197, "Hat", ItemClassification.trap),
    "Bomb Bowler":              SKPDItemData(198, "Hat", ItemClassification.trap),
    "Dungstalker":              SKPDItemData(199, "Hat", ItemClassification.trap),
    "Spinwulf Snood":           SKPDItemData(200, "Hat", ItemClassification.trap),
    "No-Peek Nightcap":         SKPDItemData(201, "Hat", ItemClassification.trap),
    "Bugle Hat":                SKPDItemData(202, "Hat", ItemClassification.filler),
    "Extrovert Hat":            SKPDItemData(203, "Hat", ItemClassification.trap),
    "Monstrous Montera":        SKPDItemData(204, "Hat", ItemClassification.trap),
    "Meager Bowler":            SKPDItemData(205, "Hat", ItemClassification.trap),
    "Deflated Beret":           SKPDItemData(206, "Hat", ItemClassification.trap),
    "Extravagant Gem Hat":      SKPDItemData(207, "Hat", ItemClassification.trap),
    "Sluggish Beeto Beret":     SKPDItemData(208, "Hat", ItemClassification.trap),
    "Red Alert Beret":          SKPDItemData(209, "Hat", ItemClassification.trap),
    "Aqualorb Hat":             SKPDItemData(210, "Hat", ItemClassification.trap),
    "Rainbowlorb Hat":          SKPDItemData(211, "Hat", ItemClassification.trap),
    "Glitzem's Top Hat":        SKPDItemData(212, "Hat", ItemClassification.trap),
    "Floatsome Fez":            SKPDItemData(213, "Hat", ItemClassification.filler),
    "Birder Bicorne":           SKPDItemData(214, "Hat", ItemClassification.trap),
    "Hoppicles Helmet":         SKPDItemData(215, "Hat", ItemClassification.trap),
    "Goldarmor Crest":          SKPDItemData(216, "Hat", ItemClassification.trap),
    "Foegenerative Cap":        SKPDItemData(217, "Hat", ItemClassification.trap),
    "Swift Spinwulf Shapka":    SKPDItemData(218, "Hat", ItemClassification.trap),
    "Memmec's Kin Cap":         SKPDItemData(219, "Hat", ItemClassification.trap),
    "Growthclang Wig":          SKPDItemData(220, "Hat", ItemClassification.trap),
    "Honcho's Headdress":       SKPDItemData(221, "Hat", ItemClassification.trap),
    "Withering Turkey Skull":   SKPDItemData(222, "Hat", ItemClassification.trap),
    "Toque Blanche":            SKPDItemData(223, "Hat", ItemClassification.trap),
    "Shoddy Helmet":            SKPDItemData(224, "Hat", ItemClassification.trap),
    "Magnetic Morion":          SKPDItemData(225, "Hat", ItemClassification.trap),
    "Stonefall Ushanka":        SKPDItemData(226, "Hat", ItemClassification.trap),
    "Wall Hat":                 SKPDItemData(227, "Hat", ItemClassification.trap),
    "Half Top Hat":             SKPDItemData(228, "Hat", ItemClassification.trap),
    "Propeller Pith Helm":      SKPDItemData(229, "Hat", ItemClassification.trap),
    "Dash Slash Cap":           SKPDItemData(230, "Hat", ItemClassification.trap),
    "Stampede Stetson":         SKPDItemData(231, "Hat", ItemClassification.trap),
    "Shop Lock Shako":          SKPDItemData(232, "Hat", ItemClassification.trap),
    "Bard's Waltzing Hat":      SKPDItemData(233, "Hat", ItemClassification.trap),
    "Transmuting Tammie":       SKPDItemData(234, "Hat", ItemClassification.trap),
    "Diluting Skullcap":        SKPDItemData(235, "Hat", ItemClassification.trap),
    "Upside-Crown":             SKPDItemData(236, "Hat", ItemClassification.trap),
    "Quester's Hat":            SKPDItemData(237, "Hat", ItemClassification.trap),
    "Cornucopia Hat":           SKPDItemData(238, "Hat", ItemClassification.trap),
    "Picklehaube":              SKPDItemData(239, "Hat", ItemClassification.trap),
    "Protracted Beeto Beret":   SKPDItemData(240, "Hat", ItemClassification.trap),
    "Boneclang Skull":          SKPDItemData(241, "Hat", ItemClassification.trap),
    "Super Skeleton Skull":     SKPDItemData(242, "Hat", ItemClassification.trap),
    "Blorb Hat":                SKPDItemData(243, "Hat", ItemClassification.trap),
    "Lavalorb Hat":             SKPDItemData(244, "Hat", ItemClassification.trap),
    "Freezorb Hat":             SKPDItemData(245, "Hat", ItemClassification.trap),
    "Needleorb Hat":            SKPDItemData(246, "Hat", ItemClassification.trap),
    "Conveyorb Hat":            SKPDItemData(247, "Hat", ItemClassification.trap),
    "Wizzem Hat":               SKPDItemData(248, "Hat", ItemClassification.trap),
    "Legendary Foe Helm":       SKPDItemData(249, "Hat", ItemClassification.trap),
    "Legendary Hazard Helm":    SKPDItemData(250, "Hat", ItemClassification.trap),
    "Invisishade Cap":          SKPDItemData(251, "Hat", ItemClassification.trap),
    "Moler Hat":                SKPDItemData(252, "Hat", ItemClassification.trap),
    "Gremlin's Cap":            SKPDItemData(253, "Hat", ItemClassification.trap),
    "Hazardous Headgear":       SKPDItemData(254, "Hat", ItemClassification.trap),
    "Terrorpin's Toque":        SKPDItemData(255, "Hat", ItemClassification.trap),
    "Snow Pelt Cap":            SKPDItemData(256, "Hat", ItemClassification.trap),
    "Troupple Acolyte's Hat":   SKPDItemData(257, "Hat", ItemClassification.trap),
    "Myopic Top Hat":           SKPDItemData(258, "Hat", ItemClassification.trap),
    "Darkness Veil":            SKPDItemData(259, "Hat", ItemClassification.trap),
    "Jack-o'-Hattern":          SKPDItemData(260, "Hat", ItemClassification.trap),
    "Toad Totem Topper":        SKPDItemData(261, "Hat", ItemClassification.trap),
    "Toxic Turban":             SKPDItemData(262, "Hat", ItemClassification.trap),
    "Goo Bumpin' Bonnet":       SKPDItemData(263, "Hat", ItemClassification.trap),
    "Cauldron Cap":             SKPDItemData(264, "Hat", ItemClassification.trap),
    "Haste Helm":               SKPDItemData(265, "Hat", ItemClassification.trap),
    "Juggler's Cap":            SKPDItemData(266, "Hat", ItemClassification.trap),
    "Wrathful Tyrolean":        SKPDItemData(267, "Hat", ItemClassification.trap),
    "Inverted Chest Hat":       SKPDItemData(268, "Hat", ItemClassification.trap),
    "Teleporter's Trapper":     SKPDItemData(269, "Hat", ItemClassification.trap),
    "Legendary Gold Helm":      SKPDItemData(270, "Hat", ItemClassification.trap),
    # "Shuffler's Hat":           SKPDItemData(271, "Hat", ItemClassification.trap),

    # "Helm of Shovelry":         SKPDItemData(272, "Hat", ItemClassification.filler),
    # "Helm of Fortune":          SKPDItemData(273, "Hat", ItemClassification.filler),
    # "Helm of Toil":             SKPDItemData(274, "Hat", ItemClassification.filler),
    # "Helm of Protection":       SKPDItemData(275, "Hat", ItemClassification.filler),
    # "Helm of Royalty":          SKPDItemData(276, "Hat", ItemClassification.filler),
    # "Helm of Torment":          SKPDItemData(278, "Hat", ItemClassification.filler),
    # "Helm of Alchemy":          SKPDItemData(279, "Hat", ItemClassification.filler),
    # "Helm of Invention":        SKPDItemData(280, "Hat", ItemClassification.filler),
    # "Helm of Fancy":            SKPDItemData(281, "Hat", ItemClassification.filler),
    # "Helm of Power":            SKPDItemData(282, "Hat", ItemClassification.filler),
    # "Helm of Vigilance":        SKPDItemData(283, "Hat", ItemClassification.filler),
    # "Helm of Hoarding":         SKPDItemData(284, "Hat", ItemClassification.filler),
    # "Helm of Refraction":       SKPDItemData(285, "Hat", ItemClassification.filler),
    # "Helm of Analysis":         SKPDItemData(286, "Hat", ItemClassification.filler),
    # "Helm of Research":         SKPDItemData(287, "Hat", ItemClassification.filler),
    # "Helm of Adaptation":       SKPDItemData(288, "Hat", ItemClassification.filler),
    # "Entrepreneurs' Lid":       SKPDItemData(289, "Hat", ItemClassification.filler),
    # "Skullcap of Fate":         SKPDItemData(290, "Hat", ItemClassification.filler),

    "Progressive Blade":        SKPDItemData(300, "Item", ItemClassification.progression), #blade can be upgraded to steel and hero blade
    "Progressive Spear":        SKPDItemData(301, "Item", ItemClassification.progression), #spear can be upgraded to super spear
    "Zap Wand":                 SKPDItemData(302, "Item", ItemClassification.progression),
    "Smoke Bomb":               SKPDItemData(303, "Item", ItemClassification.progression),
    "War Horn":                 SKPDItemData(304, "Item", ItemClassification.progression),
    "Red Troupple Chalice":     SKPDItemData(305, "Item", ItemClassification.progression),
    "Blue Troupple Chalice":    SKPDItemData(306, "Item", ItemClassification.progression),
    "Wildcard":                 SKPDItemData(307, "Item", ItemClassification.progression),
    "Chronos Coin":             SKPDItemData(308, "Item", ItemClassification.progression),
    "Ice Axe":                  SKPDItemData(309, "Item", ItemClassification.progression),
    "Fire Axe":                 SKPDItemData(310, "Item", ItemClassification.progression),
    "Shield":                   SKPDItemData(311, "Item", ItemClassification.progression),
    "Glitzemizer":              SKPDItemData(312, "Item", ItemClassification.progression),
    "Anchor":                   SKPDItemData(313, "Item", ItemClassification.progression),
    "Copycard":                 SKPDItemData(314, "Item", ItemClassification.progression),
    "Morphy Wand":              SKPDItemData(315, "Item", ItemClassification.progression),
    "Poison Dagger":            SKPDItemData(316, "Item", ItemClassification.progression),
    "Flipwand":                 SKPDItemData(317, "Item", ItemClassification.progression),
    "Portable Sploder X":       SKPDItemData(318, "Item", ItemClassification.progression),
    "Portable Sploder +":       SKPDItemData(319, "Item", ItemClassification.progression),
}