from BaseClasses import Item, ItemClassification
from typing import NamedTuple, Any

class SKPDItem(Item):
    game: str = "Shovel Knight Pocket Dungeon"

class SKPDItemData(NamedTuple):
    code: int
    category: str
    classification: ItemClassification
    internal_name: str|None = None
    data: Any = None

item_categories: dict[str, set[str]] = {}

def create_item_categories():
    for item in skpd_items:
        category = skpd_items[item].category
        if category not in item_categories:
            item_categories[category] = set()
        item_categories[category].add(item)

def get_item_from_category(category: str) -> set[str]:
    return item_categories[category]

skpd_items: dict[str, SKPDItemData] = {
    "Shop Restock":             SKPDItemData(101, "Progression", ItemClassification.progression),
    "Key Fragment":             SKPDItemData(102, "Progression", ItemClassification.progression),
    "Progressive Dungeon":      SKPDItemData(103, "Progression", ItemClassification.progression),
    "Garbage":                  SKPDItemData(291, "Filler", ItemClassification.trap),
    "1000 Gems":                SKPDItemData(292, "Filler", ItemClassification.filler),
    "2500 Gems":                SKPDItemData(294, "Filler", ItemClassification.filler),
    "5000 Gems":                SKPDItemData(295, "Filler", ItemClassification.filler),
    "Starting Relic Slot":      SKPDItemData(296, "Useful", ItemClassification.useful),

    "Shovel Knight":            SKPDItemData(104, "Character", ItemClassification.progression, "shovel knight"),
    "King Knight":              SKPDItemData(105, "Character", ItemClassification.progression, "king knight"),
    "Specter Knight":           SKPDItemData(106, "Character", ItemClassification.progression, "specter knight"),
    "Plague Knight":            SKPDItemData(107, "Character", ItemClassification.progression, "plague knight"),
    "Mole Knight":              SKPDItemData(108, "Character", ItemClassification.progression, "mole knight"),
    "Treasure Knight":          SKPDItemData(109, "Character", ItemClassification.progression, "treasure knight"),
    "Tinker Knight":            SKPDItemData(110, "Character", ItemClassification.progression, "tinker knight"),
    "Polar Knight":             SKPDItemData(111, "Character", ItemClassification.progression, "polar knight"),
    "Propeller Knight":         SKPDItemData(112, "Character", ItemClassification.progression, "propeller knight"),
    "Scrap Knight":             SKPDItemData(113, "Character", ItemClassification.progression, "scrap knight"),
    "Prism Knight":             SKPDItemData(114, "Character", ItemClassification.progression, "prism knight"),
    "Puzzle Knight":            SKPDItemData(115, "Character", ItemClassification.progression, "puzzle knight"),
    "Black Knight":             SKPDItemData(116, "Character", ItemClassification.progression, "black knight"),
    "Shield Knight":            SKPDItemData(117, "Character", ItemClassification.progression, "shield knight"),
    "Mona":                     SKPDItemData(118, "Character", ItemClassification.progression, "mona"),
    "Chester":                  SKPDItemData(119, "Character", ItemClassification.progression, "chester knight"),
    "Enchantress":              SKPDItemData(120, "Character", ItemClassification.progression, "enchantress"),
    "Quandary Sage":            SKPDItemData(121, "Character", ItemClassification.useful,      "guard knight"),
    "Spinwulf":                 SKPDItemData(122, "Character", ItemClassification.progression, "polar spinwulf"),
    "Schmutz":                  SKPDItemData(123, "Character", ItemClassification.progression, "schmutz"),
    "Beefto":                   SKPDItemData(124, "Character", ItemClassification.progression, "beefto"),

    "Shovel Knight B":          SKPDItemData(350, "Refract Character", ItemClassification.progression, "shovel knight b"),
    "King Knight B":            SKPDItemData(351, "Refract Character", ItemClassification.progression, "king knight b"),
    "Specter Knight B":         SKPDItemData(352, "Refract Character", ItemClassification.progression, "specter knight b"),
    "Plague Knight B":          SKPDItemData(353, "Refract Character", ItemClassification.progression, "plague knight b"),
    "Mole Knight B":            SKPDItemData(354, "Refract Character", ItemClassification.progression, "mole knight b"),
    "Treasure Knight B":        SKPDItemData(355, "Refract Character", ItemClassification.progression, "treasure knight b"),
    "Tinker Knight B":          SKPDItemData(356, "Refract Character", ItemClassification.progression, "tinker knight b"),
    "Polar Knight B":           SKPDItemData(357, "Refract Character", ItemClassification.progression, "polar knight b"),
    "Propeller Knight B":       SKPDItemData(358, "Refract Character", ItemClassification.progression, "propeller knight b"),
    "Scrap Knight B":           SKPDItemData(359, "Refract Character", ItemClassification.progression, "scrap knight b"),
    "Prism Knight B":           SKPDItemData(360, "Refract Character", ItemClassification.progression, "prism knight b"),
    "Puzzle Knight B":          SKPDItemData(361, "Refract Character", ItemClassification.progression, "puzzle knight b"),
    "Black Knight B":           SKPDItemData(362, "Refract Character", ItemClassification.progression, "black knight b"),
    "Shield Knight B":          SKPDItemData(363, "Refract Character", ItemClassification.progression, "shield knight b"),
    "Mona B":                   SKPDItemData(364, "Refract Character", ItemClassification.progression, "mona b"),
    "Chester B":                SKPDItemData(365, "Refract Character", ItemClassification.progression, "chester knight b"),
    "Enchantress B":            SKPDItemData(366, "Refract Character", ItemClassification.progression, "enchantress b"),

    "Meal Ticket":              SKPDItemData(127, "Relic", ItemClassification.progression,  "meal ticket",  1),
    "Premium Meal Ticket":      SKPDItemData(128, "Relic", ItemClassification.progression,  "premium ticket", 2),
    "Diamond Dust":             SKPDItemData(129, "Relic", ItemClassification.progression,  "diamond dust", 2),
    "Obsidian Drill":           SKPDItemData(130, "Relic", ItemClassification.useful,       "obsidian drill", 0),
    "Snoutin' Charm":           SKPDItemData(131, "Relic", ItemClassification.useful,       "snoutin charm", 0),
    "Shockproof Socks":         SKPDItemData(132, "Relic", ItemClassification.progression,  "shockproof socks", 1),
    "Fizzle Wand":              SKPDItemData(133, "Relic", ItemClassification.useful,       "fizzle wand", 0),
    "Bomb Seed Bag":            SKPDItemData(134, "Relic", ItemClassification.progression,  "bomb seed bag", 2),
    "Nimbus Balloon":           SKPDItemData(135, "Relic", ItemClassification.useful,       "nimbus balloon", 0),
    "Potion Napkin":            SKPDItemData(136, "Relic", ItemClassification.useful,       "potion napkin", 0),
    "Dynamallet":               SKPDItemData(137, "Relic", ItemClassification.useful,       "dynamallet", 0),
    "Power Pail":               SKPDItemData(138, "Relic", ItemClassification.progression,  "power pail", 1),
    "Desperation Talon":        SKPDItemData(139, "Relic", ItemClassification.useful,       "desperation talon", 0),
    "Gem Chain":                SKPDItemData(140, "Relic", ItemClassification.useful,       "gem chain", 0),
    "Gem Beet":                 SKPDItemData(141, "Relic", ItemClassification.useful,       "gem beet", 0),
    "Gold Leaf Clover":         SKPDItemData(142, "Relic", ItemClassification.useful,       "gold leaf clover", 0),
    "Swift Dagger":             SKPDItemData(143, "Relic", ItemClassification.progression,  "swift dagger", 3),
    "Third Amulet":             SKPDItemData(144, "Relic", ItemClassification.progression,  "third amulet", 1),
    "Single Glove":             SKPDItemData(145, "Relic", ItemClassification.progression,  "single glove", 2),
    "Divine Liquid":            SKPDItemData(146, "Relic", ItemClassification.progression,  "divine liquid", 1),
    "Five String":              SKPDItemData(147, "Relic", ItemClassification.progression,  "five string", 2),
    "Fenix Feather":            SKPDItemData(148, "Relic", ItemClassification.progression,  "fenix feather", 1),
    "Chronos Glass":            SKPDItemData(149, "Relic", ItemClassification.progression,  "chronos glass", 1),
    "Too Big Bomb":             SKPDItemData(150, "Relic", ItemClassification.progression,  "too big bomb", 1),
    "Toad Totem":               SKPDItemData(151, "Relic", ItemClassification.progression,  "toad totem", 2),
    "Mentor Manual":            SKPDItemData(152, "Relic", ItemClassification.useful,       "mentor manual", 0),
    "Fury Horns":               SKPDItemData(153, "Relic", ItemClassification.progression,  "fury horns", 1),
    "Zesty Slice":              SKPDItemData(154, "Relic", ItemClassification.progression,  "zesty slice", 1),
    "Chester's Chart":          SKPDItemData(155, "Relic", ItemClassification.useful,       "chester chart", 0),
    "Super Skeleton Key":       SKPDItemData(156, "Relic", ItemClassification.useful,       "super skeleton key", 0),
    "Ram Rod":                  SKPDItemData(157, "Relic", ItemClassification.progression,  "ram rod", 1),
    "Conjuring Cupcake":        SKPDItemData(158, "Relic", ItemClassification.progression,  "conjuring cupcake", 1),
    "Underdog Collar":          SKPDItemData(159, "Relic", ItemClassification.progression,  "underdog collar", 2),
    "Coin of Carnage":          SKPDItemData(160, "Relic", ItemClassification.progression,  "coin of carnage", 1),
    "Coin of Cover":            SKPDItemData(161, "Relic", ItemClassification.progression,  "coin of cover", 1),
    "Bountiful Bugle":          SKPDItemData(162, "Relic", ItemClassification.useful,       "bountiful bugle", 0),
    "Time Capsule":             SKPDItemData(163, "Relic", ItemClassification.useful,       "time capsule", 0),
    "Pocket Portal":            SKPDItemData(164, "Relic", ItemClassification.useful,       "pocket portal", 0),
    "Boomback Jar":             SKPDItemData(165, "Relic", ItemClassification.progression,  "explosion jar", 1),
    "Wicked Whetstone":         SKPDItemData(166, "Relic", ItemClassification.progression,  "wicked whetstone", 1),
    "Frosty Fauld":             SKPDItemData(167, "Relic", ItemClassification.progression,  "frosty fauld", 2),
    "Thorny Tambourine":        SKPDItemData(168, "Relic", ItemClassification.progression,  "thorny tambourine", 2),
    "Hearty Wandy":             SKPDItemData(169, "Relic", ItemClassification.progression,  "hearty wand", 1),
    # "Meal Coupon":              SKPDItemData(170, "Tief Relic", ItemClassification.useful,  "meal coupon"),
    # "Swift Stick":              SKPDItemData(171, "Tief Relic", ItemClassification.useful,  "swift stick"),
    # "Toad Tadpole":             SKPDItemData(172, "Tief Relic", ItemClassification.useful,  "toad tadpole"),
    # "Dubious Dust":             SKPDItemData(173, "Tief Relic", ItemClassification.useful,  "dubious dust"),
    # "Cheater Manual":           SKPDItemData(174, "Tief Relic", ItemClassification.useful,  "cheaters manual"),
    # "Apple":                    SKPDItemData(175, "Tief Relic", ItemClassification.useful,  "apple"),
    # "Cube of Lumbrix":          SKPDItemData(176, "Tief Relic", ItemClassification.useful,  "lumber cube"),
    # "Scholar's Sextant":        SKPDItemData(177, "Tief Relic", ItemClassification.useful,  "scholar sextant"),
    # "Painter Kit":              SKPDItemData(178, "Tief Relic", ItemClassification.useful,  "painter kit"),
    # "Portal Tracker":           SKPDItemData(179, "Tief Relic", ItemClassification.useful,  "portal tracker"),

    "Connoisseur's Cap":        SKPDItemData(182, "Hat", ItemClassification.filler, "discount 25"),
    "Fleeto Beret":             SKPDItemData(183, "Hat", ItemClassification.filler, "short stages"),
    "Turkey Toque":             SKPDItemData(184, "Hat", ItemClassification.filler, "turkey pots"),
    "Taming Topper":            SKPDItemData(185, "Hat", ItemClassification.filler, "underdog"),
    "Scout's Cap":              SKPDItemData(186, "Hat", ItemClassification.filler, "emergency exit"),
    "Bohto Boater":             SKPDItemData(187, "Hat", ItemClassification.filler, "more meal tickets"),
    "Present Hat":              SKPDItemData(188, "Hat", ItemClassification.filler, "exit relic"),
    "Chest Lid":                SKPDItemData(189, "Hat", ItemClassification.trap, "no items"),
    "Pauper's Cap":             SKPDItemData(190, "Hat", ItemClassification.trap, "small wallet"),
    "Herder's Hat":             SKPDItemData(191, "Hat", ItemClassification.trap, "rewardless solo kills"),
    "Platter Hatter":           SKPDItemData(192, "Hat", ItemClassification.filler, "turkey trays"),
    "Troupple Crown":           SKPDItemData(193, "Hat", ItemClassification.filler, "hp all"),
    "Mining Helmet":            SKPDItemData(194, "Hat", ItemClassification.trap, "hidden chestkey"),
    "Armorer's Bandana":        SKPDItemData(195, "Hat", ItemClassification.filler, "weapon rain"),
    "Volatile Heart Hat":       SKPDItemData(196, "Hat", ItemClassification.trap, "random hp"),
    "Summoning Slouch":         SKPDItemData(197, "Hat", ItemClassification.trap, "random units"),
    "Bomb Bowler":              SKPDItemData(198, "Hat", ItemClassification.trap, "bombs away"),
    "Dungstalker":              SKPDItemData(199, "Hat", ItemClassification.trap, "beeto breach"),
    "Spinwulf Snood":           SKPDItemData(200, "Hat", ItemClassification.trap, "spinwulf spirit"),
    "No-Peek Nightcap":         SKPDItemData(201, "Hat", ItemClassification.trap, "no UI"),
    "Bugle Hat":                SKPDItemData(202, "Hat", ItemClassification.filler, "clearance"),
    "Extrovert Hat":            SKPDItemData(203, "Hat", ItemClassification.trap, "no loners"),
    "Monstrous Montera":        SKPDItemData(204, "Hat", ItemClassification.trap, "monster"),
    "Meager Bowler":            SKPDItemData(205, "Hat", ItemClassification.trap, "out of stock"),
    "Deflated Beret":           SKPDItemData(206, "Hat", ItemClassification.trap, "tax hike"),
    "Extravagant Gem Hat":      SKPDItemData(207, "Hat", ItemClassification.trap, "relic price up"),
    "Sluggish Beeto Beret":     SKPDItemData(208, "Hat", ItemClassification.trap, "longer levels"),
    "Red Alert Beret":          SKPDItemData(209, "Hat", ItemClassification.trap, "traffic mode"),
    "Aqualorb Hat":             SKPDItemData(210, "Hat", ItemClassification.trap, "floor water"),
    "Rainbowlorb Hat":          SKPDItemData(211, "Hat", ItemClassification.trap, "random hazards"),
    "Glitzem's Top Hat":        SKPDItemData(212, "Hat", ItemClassification.trap, "gacha relics"),
    "Floatsome Fez":            SKPDItemData(213, "Hat", ItemClassification.filler, "low gravity"),
    "Birder Bicorne":           SKPDItemData(214, "Hat", ItemClassification.trap, "birder"),
    "Hoppicles Helmet":         SKPDItemData(215, "Hat", ItemClassification.trap, "no backtracks"),
    "Goldarmor Crest":          SKPDItemData(216, "Hat", ItemClassification.trap, "reinforcements"),
    "Foegenerative Cap":        SKPDItemData(217, "Hat", ItemClassification.trap, "enemy autoheal"),
    "Swift Spinwulf Shapka":    SKPDItemData(218, "Hat", ItemClassification.trap, "faster turns"),
    "Memmec's Kin Cap":         SKPDItemData(219, "Hat", ItemClassification.trap, "memmec chests"),
    "Growthclang Wig":          SKPDItemData(220, "Hat", ItemClassification.trap, "gem skeletons"),
    "Honcho's Headdress":       SKPDItemData(221, "Hat", ItemClassification.trap, "necromancy"),
    "Withering Turkey Skull":   SKPDItemData(222, "Hat", ItemClassification.trap, "less hp player"),
    "Toque Blanche":            SKPDItemData(223, "Hat", ItemClassification.trap, "more hp enemies"),
    "Shoddy Helmet":            SKPDItemData(224, "Hat", ItemClassification.trap, "half durability"),
    "Magnetic Morion":          SKPDItemData(225, "Hat", ItemClassification.trap, "all tangle"),
    "Stonefall Ushanka":        SKPDItemData(226, "Hat", ItemClassification.trap, "player gravity"),
    "Wall Hat":                 SKPDItemData(227, "Hat", ItemClassification.trap, "row spawner"),
    "Half Top Hat":             SKPDItemData(228, "Hat", ItemClassification.trap, "gems halved"),
    "Propeller Pith Helm":      SKPDItemData(229, "Hat", ItemClassification.trap, "no gravity"),
    "Dash Slash Cap":           SKPDItemData(230, "Hat", ItemClassification.trap, "autoslice"),
    "Stampede Stetson":         SKPDItemData(231, "Hat", ItemClassification.trap, "stampede"),
    "Shop Lock Shako":          SKPDItemData(232, "Hat", ItemClassification.trap, "no relics"),
    "Bard's Waltzing Hat":      SKPDItemData(233, "Hat", ItemClassification.trap, "waltz walk"),
    "Transmuting Tammie":       SKPDItemData(234, "Hat", ItemClassification.trap, "items change on use"),
    "Diluting Skullcap":        SKPDItemData(235, "Hat", ItemClassification.trap, "expiration date"),
    "Upside-Crown":             SKPDItemData(236, "Hat", ItemClassification.trap, "down spawner"),
    "Quester's Hat":            SKPDItemData(237, "Hat", ItemClassification.trap, "character quest"),
    "Cornucopia Hat":           SKPDItemData(238, "Hat", ItemClassification.trap, "offering trial"),
    "Picklehaube":              SKPDItemData(239, "Hat", ItemClassification.trap, "pickles"),
    "Protracted Beeto Beret":   SKPDItemData(240, "Hat", ItemClassification.trap, "super long levels"),
    "Boneclang Skull":          SKPDItemData(241, "Hat", ItemClassification.trap, "throwback"),
    "Super Skeleton Skull":     SKPDItemData(242, "Hat", ItemClassification.trap, "tag team"),
    "Blorb Hat":                SKPDItemData(243, "Hat", ItemClassification.trap, "floor poison"),
    "Lavalorb Hat":             SKPDItemData(244, "Hat", ItemClassification.trap, "floor lava"),
    "Freezorb Hat":             SKPDItemData(245, "Hat", ItemClassification.trap, "floor ice"),
    "Needleorb Hat":            SKPDItemData(246, "Hat", ItemClassification.trap, "floor spikes"),
    "Conveyorb Hat":            SKPDItemData(247, "Hat", ItemClassification.trap, "floor conveyors"),
    "Wizzem Hat":               SKPDItemData(248, "Hat", ItemClassification.trap, "crystal mirror"),
    "Legendary Foe Helm":       SKPDItemData(249, "Hat", ItemClassification.trap, "advanced spawns"),
    "Legendary Hazard Helm":    SKPDItemData(250, "Hat", ItemClassification.trap, "advanced hazards"),
    "Invisishade Cap":          SKPDItemData(251, "Hat", ItemClassification.trap, "enchantress ghost"),
    "Moler Hat":                SKPDItemData(252, "Hat", ItemClassification.trap, "buried mode"),
    "Gremlin's Cap":            SKPDItemData(253, "Hat", ItemClassification.trap, "relic snare"),
    "Hazardous Headgear":       SKPDItemData(254, "Hat", ItemClassification.trap, "hazards always"),
    "Terrorpin's Toque":        SKPDItemData(255, "Hat", ItemClassification.trap, "terrorpin"),
    "Snow Pelt Cap":            SKPDItemData(256, "Hat", ItemClassification.trap, "avalanches"),
    "Troupple Acolyte's Hat":   SKPDItemData(257, "Hat", ItemClassification.trap, "double HP"),
    "Myopic Top Hat":           SKPDItemData(258, "Hat", ItemClassification.trap, "hp fog"),
    "Darkness Veil":            SKPDItemData(259, "Hat", ItemClassification.trap, "dark fog"),
    "Jack-o'-Hattern":          SKPDItemData(260, "Hat", ItemClassification.trap, "lights out"),
    "Toad Totem Topper":        SKPDItemData(261, "Hat", ItemClassification.trap, "pandemic"),
    "Toxic Turban":             SKPDItemData(262, "Hat", ItemClassification.trap, "all poisonous"),
    "Goo Bumpin' Bonnet":       SKPDItemData(263, "Hat", ItemClassification.trap, "push attack"),
    "Cauldron Cap":             SKPDItemData(264, "Hat", ItemClassification.trap, "cauldrons"),
    "Haste Helm":               SKPDItemData(265, "Hat", ItemClassification.trap, "turbo"),
    "Juggler's Cap":            SKPDItemData(266, "Hat", ItemClassification.trap, "chaos"),
    "Wrathful Tyrolean":        SKPDItemData(267, "Hat", ItemClassification.trap, "damage buff"),
    "Inverted Chest Hat":       SKPDItemData(268, "Hat", ItemClassification.trap, "buy weapons"),
    "Teleporter's Trapper":     SKPDItemData(269, "Hat", ItemClassification.trap, "magic floors"),
    "Legendary Gold Helm":      SKPDItemData(270, "Hat", ItemClassification.trap, "advanced mode"),
    "Shuffler's Hat":           SKPDItemData(271, "Hat", ItemClassification.trap, "hat shuffler"),

    # "Progressive Blade":        SKPDItemData(300, "Item", ItemClassification.progression), #blade can be upgraded to steel and hero blade
    # "Progressive Spear":        SKPDItemData(301, "Item", ItemClassification.progression), #spear can be upgraded to super spear
    # "Zap Wand":                 SKPDItemData(302, "Item", ItemClassification.progression, "zap wand"),
    # "Smoke Bomb":               SKPDItemData(303, "Item", ItemClassification.progression, "smoke bomb"),
    # "War Horn":                 SKPDItemData(304, "Item", ItemClassification.progression, "war horn"),
    # "Red Troupple Chalice":     SKPDItemData(305, "Item", ItemClassification.progression, "red troupple chalice"),
    # "Blue Troupple Chalice":    SKPDItemData(306, "Item", ItemClassification.progression, "blue troupple chalice"),
    # "Wildcard":                 SKPDItemData(307, "Item", ItemClassification.progression, "wildcard"),
    # "Chronos Coin":             SKPDItemData(308, "Item", ItemClassification.progression, "chronos coin"),
    # "Ice Axe":                  SKPDItemData(309, "Item", ItemClassification.progression, "ice axe"),
    # "Fire Axe":                 SKPDItemData(310, "Item", ItemClassification.progression, "fire axe"),
    # "Shield":                   SKPDItemData(311, "Item", ItemClassification.progression, "shield"),
    # "Glitzemizer":              SKPDItemData(312, "Item", ItemClassification.progression, "glitzemizer"),
    # "Anchor":                   SKPDItemData(313, "Item", ItemClassification.progression, "anchor"),
    # "Copycard":                 SKPDItemData(314, "Item", ItemClassification.progression, "copycard"),
    # "Morphy Wand":              SKPDItemData(315, "Item", ItemClassification.progression, "magic wand"),
    # "Poison Dagger":            SKPDItemData(316, "Item", ItemClassification.progression, "poison dagger"),
    # "Flipwand":                 SKPDItemData(317, "Item", ItemClassification.progression, "flipwand"),
    # "Portable Sploder X":       SKPDItemData(318, "Item", ItemClassification.progression, "exploder X"),
    # "Portable Sploder +":       SKPDItemData(319, "Item", ItemClassification.progression, "exploder T"),
}

item_dict = {name: data.code for name, data in skpd_items.items()}