from BaseClasses import Item, ItemClassification
from typing import NamedTuple, Any
from enum import Enum

class SKPDItemCategory(Enum):
    PROGRESSION = 0
    USEFUL = 1
    FILLER = 2
    CHARACTER = 3
    REFRACT_CHARACTER = 4
    RELIC = 5
    HAT = 6
    ITEM = 7

class SKPDItem(Item):
    game: str = "Shovel Knight Pocket Dungeon"

class SKPDItemData(NamedTuple):
    code: int
    category: SKPDItemCategory
    classification: ItemClassification
    internal_name: str|None = None
    data: Any = None

item_categories: dict[SKPDItemCategory, list[str]] = {}

def create_item_categories():
    for item in skpd_items:
        category = skpd_items[item].category
        if category not in item_categories:
            item_categories[category] = list()
        item_categories[category].append(item)

def get_item_from_category(category: SKPDItemCategory) -> list[str]:
    return item_categories[category]

skpd_items: dict[str, SKPDItemData] = {
    "Shop Restock":             SKPDItemData(101, SKPDItemCategory.PROGRESSION, ItemClassification.progression),
    "Key Fragment":             SKPDItemData(102, SKPDItemCategory.PROGRESSION, ItemClassification.progression),
    "Progressive Dungeon":      SKPDItemData(103, SKPDItemCategory.PROGRESSION, ItemClassification.progression),
    "Garbage":                  SKPDItemData(291, SKPDItemCategory.FILLER, ItemClassification.trap),
    "1000 Gems":                SKPDItemData(292, SKPDItemCategory.FILLER, ItemClassification.filler),
    "2500 Gems":                SKPDItemData(294, SKPDItemCategory.FILLER, ItemClassification.filler),
    "5000 Gems":                SKPDItemData(295, SKPDItemCategory.FILLER, ItemClassification.filler),
    "Starting Relic Slot":      SKPDItemData(296, SKPDItemCategory.USEFUL, ItemClassification.useful),

    "Shovel Knight":            SKPDItemData(104, SKPDItemCategory.CHARACTER, ItemClassification.progression, "shovel knight"),
    "King Knight":              SKPDItemData(105, SKPDItemCategory.CHARACTER, ItemClassification.progression, "king knight"),
    "Specter Knight":           SKPDItemData(106, SKPDItemCategory.CHARACTER, ItemClassification.progression, "specter knight"),
    "Plague Knight":            SKPDItemData(107, SKPDItemCategory.CHARACTER, ItemClassification.progression, "plague knight"),
    "Mole Knight":              SKPDItemData(108, SKPDItemCategory.CHARACTER, ItemClassification.progression, "mole knight"),
    "Treasure Knight":          SKPDItemData(109, SKPDItemCategory.CHARACTER, ItemClassification.progression, "treasure knight"),
    "Tinker Knight":            SKPDItemData(110, SKPDItemCategory.CHARACTER, ItemClassification.progression, "tinker knight"),
    "Polar Knight":             SKPDItemData(111, SKPDItemCategory.CHARACTER, ItemClassification.progression, "polar knight"),
    "Propeller Knight":         SKPDItemData(112, SKPDItemCategory.CHARACTER, ItemClassification.progression, "propeller knight"),
    "Scrap Knight":             SKPDItemData(113, SKPDItemCategory.CHARACTER, ItemClassification.progression, "scrap knight"),
    "Prism Knight":             SKPDItemData(114, SKPDItemCategory.CHARACTER, ItemClassification.progression, "prism knight"),
    "Puzzle Knight":            SKPDItemData(115, SKPDItemCategory.CHARACTER, ItemClassification.progression, "puzzle knight"),
    "Black Knight":             SKPDItemData(116, SKPDItemCategory.CHARACTER, ItemClassification.progression, "black knight"),
    "Shield Knight":            SKPDItemData(117, SKPDItemCategory.CHARACTER, ItemClassification.progression, "shield knight"),
    "Mona":                     SKPDItemData(118, SKPDItemCategory.CHARACTER, ItemClassification.progression, "mona"),
    "Chester":                  SKPDItemData(119, SKPDItemCategory.CHARACTER, ItemClassification.progression, "chester knight"),
    "Enchantress":              SKPDItemData(120, SKPDItemCategory.CHARACTER, ItemClassification.progression, "enchantress"),
    "Quandary Sage":            SKPDItemData(121, SKPDItemCategory.CHARACTER, ItemClassification.progression, "guard knight"),
    "Spinwulf":                 SKPDItemData(122, SKPDItemCategory.CHARACTER, ItemClassification.progression, "polar spinwulf"),
    "Schmutz":                  SKPDItemData(123, SKPDItemCategory.CHARACTER, ItemClassification.progression, "schmutz"),
    "Beefto":                   SKPDItemData(124, SKPDItemCategory.CHARACTER, ItemClassification.progression, "beefto"),

    "Shovel Knight B":          SKPDItemData(350, SKPDItemCategory.REFRACT_CHARACTER, ItemClassification.progression, "shovel knight b"),
    "King Knight B":            SKPDItemData(351, SKPDItemCategory.REFRACT_CHARACTER, ItemClassification.progression, "king knight b"),
    "Specter Knight B":         SKPDItemData(352, SKPDItemCategory.REFRACT_CHARACTER, ItemClassification.progression, "specter knight b"),
    "Plague Knight B":          SKPDItemData(353, SKPDItemCategory.REFRACT_CHARACTER, ItemClassification.progression, "plague knight b"),
    "Mole Knight B":            SKPDItemData(354, SKPDItemCategory.REFRACT_CHARACTER, ItemClassification.progression, "mole knight b"),
    "Treasure Knight B":        SKPDItemData(355, SKPDItemCategory.REFRACT_CHARACTER, ItemClassification.progression, "treasure knight b"),
    "Tinker Knight B":          SKPDItemData(356, SKPDItemCategory.REFRACT_CHARACTER, ItemClassification.progression, "tinker knight b"),
    "Polar Knight B":           SKPDItemData(357, SKPDItemCategory.REFRACT_CHARACTER, ItemClassification.progression, "polar knight b"),
    "Propeller Knight B":       SKPDItemData(358, SKPDItemCategory.REFRACT_CHARACTER, ItemClassification.progression, "propeller knight b"),
    "Scrap Knight B":           SKPDItemData(359, SKPDItemCategory.REFRACT_CHARACTER, ItemClassification.progression, "scrap knight b"),
    "Prism Knight B":           SKPDItemData(360, SKPDItemCategory.REFRACT_CHARACTER, ItemClassification.progression, "prism knight b"),
    "Puzzle Knight B":          SKPDItemData(361, SKPDItemCategory.REFRACT_CHARACTER, ItemClassification.progression, "puzzle knight b"),
    "Black Knight B":           SKPDItemData(362, SKPDItemCategory.REFRACT_CHARACTER, ItemClassification.progression, "black knight b"),
    "Shield Knight B":          SKPDItemData(363, SKPDItemCategory.REFRACT_CHARACTER, ItemClassification.progression, "shield knight b"),
    "Mona B":                   SKPDItemData(364, SKPDItemCategory.REFRACT_CHARACTER, ItemClassification.progression, "mona b"),
    "Chester B":                SKPDItemData(365, SKPDItemCategory.REFRACT_CHARACTER, ItemClassification.progression, "chester knight b"),
    "Enchantress B":            SKPDItemData(366, SKPDItemCategory.REFRACT_CHARACTER, ItemClassification.progression, "enchantress b"),

    "Meal Ticket":              SKPDItemData(127, SKPDItemCategory.RELIC, ItemClassification.progression,  "meal ticket",  1),
    "Premium Meal Ticket":      SKPDItemData(128, SKPDItemCategory.RELIC, ItemClassification.progression,  "premium ticket", 2),
    "Diamond Dust":             SKPDItemData(129, SKPDItemCategory.RELIC, ItemClassification.progression,  "diamond dust", 2),
    "Obsidian Drill":           SKPDItemData(130, SKPDItemCategory.RELIC, ItemClassification.useful,       "obsidian drill", 0),
    "Snoutin' Charm":           SKPDItemData(131, SKPDItemCategory.RELIC, ItemClassification.useful,       "snoutin charm", 0),
    "Shockproof Socks":         SKPDItemData(132, SKPDItemCategory.RELIC, ItemClassification.progression,  "shockproof socks", 1),
    "Fizzle Wand":              SKPDItemData(133, SKPDItemCategory.RELIC, ItemClassification.useful,       "fizzle wand", 0),
    "Bomb Seed Bag":            SKPDItemData(134, SKPDItemCategory.RELIC, ItemClassification.progression,  "bomb seed bag", 2),
    "Nimbus Balloon":           SKPDItemData(135, SKPDItemCategory.RELIC, ItemClassification.useful,       "nimbus balloon", 0),
    "Potion Napkin":            SKPDItemData(136, SKPDItemCategory.RELIC, ItemClassification.useful,       "potion napkin", 0),
    "Dynamallet":               SKPDItemData(137, SKPDItemCategory.RELIC, ItemClassification.useful,       "dynamallet", 0),
    "Power Pail":               SKPDItemData(138, SKPDItemCategory.RELIC, ItemClassification.progression,  "power pail", 1),
    "Desperation Talon":        SKPDItemData(139, SKPDItemCategory.RELIC, ItemClassification.useful,       "desperation talon", 0),
    "Gem Chain":                SKPDItemData(140, SKPDItemCategory.RELIC, ItemClassification.useful,       "gem chain", 0),
    "Gem Beet":                 SKPDItemData(141, SKPDItemCategory.RELIC, ItemClassification.useful,       "gem beet", 0),
    "Gold Leaf Clover":         SKPDItemData(142, SKPDItemCategory.RELIC, ItemClassification.useful,       "gold leaf clover", 0),
    "Swift Dagger":             SKPDItemData(143, SKPDItemCategory.RELIC, ItemClassification.progression,  "swift dagger", 3),
    "Third Amulet":             SKPDItemData(144, SKPDItemCategory.RELIC, ItemClassification.progression,  "third amulet", 1),
    "Single Glove":             SKPDItemData(145, SKPDItemCategory.RELIC, ItemClassification.progression,  "single glove", 2),
    "Divine Liquid":            SKPDItemData(146, SKPDItemCategory.RELIC, ItemClassification.progression,  "divine liquid", 1),
    "Five String":              SKPDItemData(147, SKPDItemCategory.RELIC, ItemClassification.progression,  "five string", 2),
    "Fenix Feather":            SKPDItemData(148, SKPDItemCategory.RELIC, ItemClassification.progression,  "fenix feather", 1),
    "Chronos Glass":            SKPDItemData(149, SKPDItemCategory.RELIC, ItemClassification.progression,  "chronos glass", 1),
    "Too Big Bomb":             SKPDItemData(150, SKPDItemCategory.RELIC, ItemClassification.progression,  "too big bomb", 1),
    "Toad Totem":               SKPDItemData(151, SKPDItemCategory.RELIC, ItemClassification.progression,  "toad totem", 2),
    "Mentor Manual":            SKPDItemData(152, SKPDItemCategory.RELIC, ItemClassification.useful,       "mentor manual", 0),
    "Fury Horns":               SKPDItemData(153, SKPDItemCategory.RELIC, ItemClassification.progression,  "fury horns", 1),
    "Zesty Slice":              SKPDItemData(154, SKPDItemCategory.RELIC, ItemClassification.progression,  "zesty slice", 1),
    "Chester's Chart":          SKPDItemData(155, SKPDItemCategory.RELIC, ItemClassification.useful,       "chester chart", 0),
    "Super Skeleton Key":       SKPDItemData(156, SKPDItemCategory.RELIC, ItemClassification.useful,       "super skeleton key", 0),
    "Ram Rod":                  SKPDItemData(157, SKPDItemCategory.RELIC, ItemClassification.progression,  "ram rod", 1),
    "Conjuring Cupcake":        SKPDItemData(158, SKPDItemCategory.RELIC, ItemClassification.progression,  "conjuring cupcake", 1),
    "Underdog Collar":          SKPDItemData(159, SKPDItemCategory.RELIC, ItemClassification.progression,  "underdog collar", 2),
    "Coin of Carnage":          SKPDItemData(160, SKPDItemCategory.RELIC, ItemClassification.progression,  "coin of carnage", 1),
    "Coin of Cover":            SKPDItemData(161, SKPDItemCategory.RELIC, ItemClassification.progression,  "coin of cover", 1),
    "Bountiful Bugle":          SKPDItemData(162, SKPDItemCategory.RELIC, ItemClassification.useful,       "bountiful bugle", 0),
    "Time Capsule":             SKPDItemData(163, SKPDItemCategory.RELIC, ItemClassification.useful,       "time capsule", 0),
    "Pocket Portal":            SKPDItemData(164, SKPDItemCategory.RELIC, ItemClassification.useful,       "pocket portal", 0),
    "Boomback Jar":             SKPDItemData(165, SKPDItemCategory.RELIC, ItemClassification.progression,  "explosion jar", 1),
    "Wicked Whetstone":         SKPDItemData(166, SKPDItemCategory.RELIC, ItemClassification.progression,  "wicked whetstone", 1),
    "Frosty Fauld":             SKPDItemData(167, SKPDItemCategory.RELIC, ItemClassification.progression,  "frosty fauld", 2),
    "Thorny Tambourine":        SKPDItemData(168, SKPDItemCategory.RELIC, ItemClassification.progression,  "thorny tambourine", 2),
    "Hearty Wandy":             SKPDItemData(169, SKPDItemCategory.RELIC, ItemClassification.progression,  "hearty wand", 1),
    # "Meal Coupon":              SKPDItemData(170, "Tief Relic", ItemClassification.useful,  "meal coupon"),
    # "Swift Stick":              SKPDItemData(171, "Tief Relic", ItemClassification.useful,  "swift stick"),
    # "Toad Tadpole":             SKPDItemData(172, "Tief Relic", ItemClassification.useful,  "toad tadpole"),
    # "Dubious Dust":             SKPDItemData(173, "Tief Relic", ItemClassification.useful,  "dubious dust"),
    # "Cheater Manual":           SKPDItemData(174, "Tief Relic", ItemClassification.useful,  "cheaters manual"),
    # "Apple":                    SKPDItemData(175, "Tief Relic", ItemClassification.useful,  "apple"),
    # "Cube of Lumbrix":          SKPDItemData(176, "Tief Relic", ItemClassification.useful,  "lumber cube"),
    # "Scholar's Sextant":        SKPDItemData(177, "Tief Relic", ItemClassification.useful,  "scholar sextant"),
    # "Painter Kit":              SKPDItemData(178, "Tief Relic", ItemClassification.useful,  "painter kit"),
    # "Portal Tracker":           SKPDItemData(179, "Tief Relic", ItemClassification.useful,  "portal tracker"),

    "Connoisseur's Cap":        SKPDItemData(182, SKPDItemCategory.HAT, ItemClassification.filler, "discount 25"),
    "Fleeto Beret":             SKPDItemData(183, SKPDItemCategory.HAT, ItemClassification.filler, "short stages"),
    "Turkey Toque":             SKPDItemData(184, SKPDItemCategory.HAT, ItemClassification.filler, "turkey pots"),
    "Taming Topper":            SKPDItemData(185, SKPDItemCategory.HAT, ItemClassification.filler, "underdog"),
    "Scout's Cap":              SKPDItemData(186, SKPDItemCategory.HAT, ItemClassification.filler, "emergency exit"),
    "Bohto Boater":             SKPDItemData(187, SKPDItemCategory.HAT, ItemClassification.filler, "more meal tickets"),
    "Present Hat":              SKPDItemData(188, SKPDItemCategory.HAT, ItemClassification.filler, "exit relic"),
    "Chest Lid":                SKPDItemData(189, SKPDItemCategory.HAT, ItemClassification.trap, "no items"),
    "Pauper's Cap":             SKPDItemData(190, SKPDItemCategory.HAT, ItemClassification.trap, "small wallet"),
    "Herder's Hat":             SKPDItemData(191, SKPDItemCategory.HAT, ItemClassification.trap, "rewardless solo kills"),
    "Platter Hatter":           SKPDItemData(192, SKPDItemCategory.HAT, ItemClassification.filler, "turkey trays"),
    "Troupple Crown":           SKPDItemData(193, SKPDItemCategory.HAT, ItemClassification.filler, "hp all"),
    "Mining Helmet":            SKPDItemData(194, SKPDItemCategory.HAT, ItemClassification.trap, "hidden chestkey"),
    "Armorer's Bandana":        SKPDItemData(195, SKPDItemCategory.HAT, ItemClassification.filler, "weapon rain"),
    "Volatile Heart Hat":       SKPDItemData(196, SKPDItemCategory.HAT, ItemClassification.trap, "random hp"),
    "Summoning Slouch":         SKPDItemData(197, SKPDItemCategory.HAT, ItemClassification.trap, "random units"),
    "Bomb Bowler":              SKPDItemData(198, SKPDItemCategory.HAT, ItemClassification.trap, "bombs away"),
    "Dungstalker":              SKPDItemData(199, SKPDItemCategory.HAT, ItemClassification.trap, "beeto breach"),
    "Spinwulf Snood":           SKPDItemData(200, SKPDItemCategory.HAT, ItemClassification.trap, "spinwulf spirit"),
    "No-Peek Nightcap":         SKPDItemData(201, SKPDItemCategory.HAT, ItemClassification.trap, "no UI"),
    "Bugle Hat":                SKPDItemData(202, SKPDItemCategory.HAT, ItemClassification.filler, "clearance"),
    "Extrovert Hat":            SKPDItemData(203, SKPDItemCategory.HAT, ItemClassification.trap, "no loners"),
    "Monstrous Montera":        SKPDItemData(204, SKPDItemCategory.HAT, ItemClassification.trap, "monster"),
    "Meager Bowler":            SKPDItemData(205, SKPDItemCategory.HAT, ItemClassification.trap, "out of stock"),
    "Deflated Beret":           SKPDItemData(206, SKPDItemCategory.HAT, ItemClassification.trap, "tax hike"),
    "Extravagant Gem Hat":      SKPDItemData(207, SKPDItemCategory.HAT, ItemClassification.trap, "relic price up"),
    "Sluggish Beeto Beret":     SKPDItemData(208, SKPDItemCategory.HAT, ItemClassification.trap, "longer levels"),
    "Red Alert Beret":          SKPDItemData(209, SKPDItemCategory.HAT, ItemClassification.trap, "traffic mode"),
    "Aqualorb Hat":             SKPDItemData(210, SKPDItemCategory.HAT, ItemClassification.trap, "floor water"),
    "Rainbowlorb Hat":          SKPDItemData(211, SKPDItemCategory.HAT, ItemClassification.trap, "random hazards"),
    "Glitzem's Top Hat":        SKPDItemData(212, SKPDItemCategory.HAT, ItemClassification.trap, "gacha relics"),
    "Floatsome Fez":            SKPDItemData(213, SKPDItemCategory.HAT, ItemClassification.filler, "low gravity"),
    "Birder Bicorne":           SKPDItemData(214, SKPDItemCategory.HAT, ItemClassification.trap, "birder"),
    "Hoppicles Helmet":         SKPDItemData(215, SKPDItemCategory.HAT, ItemClassification.trap, "no backtracks"),
    "Goldarmor Crest":          SKPDItemData(216, SKPDItemCategory.HAT, ItemClassification.trap, "reinforcements"),
    "Foegenerative Cap":        SKPDItemData(217, SKPDItemCategory.HAT, ItemClassification.trap, "enemy autoheal"),
    "Swift Spinwulf Shapka":    SKPDItemData(218, SKPDItemCategory.HAT, ItemClassification.trap, "faster turns"),
    "Memmec's Kin Cap":         SKPDItemData(219, SKPDItemCategory.HAT, ItemClassification.trap, "memmec chests"),
    "Growthclang Wig":          SKPDItemData(220, SKPDItemCategory.HAT, ItemClassification.trap, "gem skeletons"),
    "Honcho's Headdress":       SKPDItemData(221, SKPDItemCategory.HAT, ItemClassification.trap, "necromancy"),
    "Withering Turkey Skull":   SKPDItemData(222, SKPDItemCategory.HAT, ItemClassification.trap, "less hp player"),
    "Toque Blanche":            SKPDItemData(223, SKPDItemCategory.HAT, ItemClassification.trap, "more hp enemies"),
    "Shoddy Helmet":            SKPDItemData(224, SKPDItemCategory.HAT, ItemClassification.trap, "half durability"),
    "Magnetic Morion":          SKPDItemData(225, SKPDItemCategory.HAT, ItemClassification.trap, "all tangle"),
    "Stonefall Ushanka":        SKPDItemData(226, SKPDItemCategory.HAT, ItemClassification.trap, "player gravity"),
    "Wall Hat":                 SKPDItemData(227, SKPDItemCategory.HAT, ItemClassification.trap, "row spawner"),
    "Half Top Hat":             SKPDItemData(228, SKPDItemCategory.HAT, ItemClassification.trap, "gems halved"),
    "Propeller Pith Helm":      SKPDItemData(229, SKPDItemCategory.HAT, ItemClassification.trap, "no gravity"),
    "Dash Slash Cap":           SKPDItemData(230, SKPDItemCategory.HAT, ItemClassification.trap, "autoslice"),
    "Stampede Stetson":         SKPDItemData(231, SKPDItemCategory.HAT, ItemClassification.trap, "stampede"),
    "Shop Lock Shako":          SKPDItemData(232, SKPDItemCategory.HAT, ItemClassification.trap, "no relics"),
    "Bard's Waltzing Hat":      SKPDItemData(233, SKPDItemCategory.HAT, ItemClassification.trap, "waltz walk"),
    "Transmuting Tammie":       SKPDItemData(234, SKPDItemCategory.HAT, ItemClassification.trap, "items change on use"),
    "Diluting Skullcap":        SKPDItemData(235, SKPDItemCategory.HAT, ItemClassification.trap, "expiration date"),
    "Upside-Crown":             SKPDItemData(236, SKPDItemCategory.HAT, ItemClassification.trap, "down spawner"),
    "Quester's Hat":            SKPDItemData(237, SKPDItemCategory.HAT, ItemClassification.trap, "character quest"),
    "Cornucopia Hat":           SKPDItemData(238, SKPDItemCategory.HAT, ItemClassification.trap, "offering trial"),
    "Picklehaube":              SKPDItemData(239, SKPDItemCategory.HAT, ItemClassification.trap, "pickles"),
    "Protracted Beeto Beret":   SKPDItemData(240, SKPDItemCategory.HAT, ItemClassification.trap, "super long levels"),
    "Boneclang Skull":          SKPDItemData(241, SKPDItemCategory.HAT, ItemClassification.trap, "throwback"),
    "Super Skeleton Skull":     SKPDItemData(242, SKPDItemCategory.HAT, ItemClassification.trap, "tag team"),
    "Blorb Hat":                SKPDItemData(243, SKPDItemCategory.HAT, ItemClassification.trap, "floor poison"),
    "Lavalorb Hat":             SKPDItemData(244, SKPDItemCategory.HAT, ItemClassification.trap, "floor lava"),
    "Freezorb Hat":             SKPDItemData(245, SKPDItemCategory.HAT, ItemClassification.trap, "floor ice"),
    "Needleorb Hat":            SKPDItemData(246, SKPDItemCategory.HAT, ItemClassification.trap, "floor spikes"),
    "Conveyorb Hat":            SKPDItemData(247, SKPDItemCategory.HAT, ItemClassification.trap, "floor conveyors"),
    "Wizzem Hat":               SKPDItemData(248, SKPDItemCategory.HAT, ItemClassification.trap, "crystal mirror"),
    "Legendary Foe Helm":       SKPDItemData(249, SKPDItemCategory.HAT, ItemClassification.trap, "advanced spawns"),
    "Legendary Hazard Helm":    SKPDItemData(250, SKPDItemCategory.HAT, ItemClassification.trap, "advanced hazards"),
    "Invisishade Cap":          SKPDItemData(251, SKPDItemCategory.HAT, ItemClassification.trap, "enchantress ghost"),
    "Moler Hat":                SKPDItemData(252, SKPDItemCategory.HAT, ItemClassification.trap, "buried mode"),
    "Gremlin's Cap":            SKPDItemData(253, SKPDItemCategory.HAT, ItemClassification.trap, "relic snare"),
    "Hazardous Headgear":       SKPDItemData(254, SKPDItemCategory.HAT, ItemClassification.trap, "hazards always"),
    "Terrorpin's Toque":        SKPDItemData(255, SKPDItemCategory.HAT, ItemClassification.trap, "terrorpin"),
    "Snow Pelt Cap":            SKPDItemData(256, SKPDItemCategory.HAT, ItemClassification.trap, "avalanches"),
    "Troupple Acolyte's Hat":   SKPDItemData(257, SKPDItemCategory.HAT, ItemClassification.trap, "double HP"),
    "Myopic Top Hat":           SKPDItemData(258, SKPDItemCategory.HAT, ItemClassification.trap, "hp fog"),
    "Darkness Veil":            SKPDItemData(259, SKPDItemCategory.HAT, ItemClassification.trap, "dark fog"),
    "Jack-o'-Hattern":          SKPDItemData(260, SKPDItemCategory.HAT, ItemClassification.trap, "lights out"),
    "Toad Totem Topper":        SKPDItemData(261, SKPDItemCategory.HAT, ItemClassification.trap, "pandemic"),
    "Toxic Turban":             SKPDItemData(262, SKPDItemCategory.HAT, ItemClassification.trap, "all poisonous"),
    "Goo Bumpin' Bonnet":       SKPDItemData(263, SKPDItemCategory.HAT, ItemClassification.trap, "push attack"),
    "Cauldron Cap":             SKPDItemData(264, SKPDItemCategory.HAT, ItemClassification.trap, "cauldrons"),
    "Haste Helm":               SKPDItemData(265, SKPDItemCategory.HAT, ItemClassification.trap, "turbo"),
    "Juggler's Cap":            SKPDItemData(266, SKPDItemCategory.HAT, ItemClassification.trap, "chaos"),
    "Wrathful Tyrolean":        SKPDItemData(267, SKPDItemCategory.HAT, ItemClassification.trap, "damage buff"),
    "Inverted Chest Hat":       SKPDItemData(268, SKPDItemCategory.HAT, ItemClassification.trap, "buy weapons"),
    "Teleporter's Trapper":     SKPDItemData(269, SKPDItemCategory.HAT, ItemClassification.trap, "magic floors"),
    "Legendary Gold Helm":      SKPDItemData(270, SKPDItemCategory.HAT, ItemClassification.trap, "advanced mode"),
    "Shuffler's Hat":           SKPDItemData(271, SKPDItemCategory.HAT, ItemClassification.trap, "hat shuffler"),

    # "Progressive Blade":        SKPDItemData(300, "Item", ItemClassification.progression), #blade can be upgraded to steel and hero blade
    # "Progressive Spear":        SKPDItemData(301, "Item", ItemClassification.progression), #spear can be upgraded to super spear
    # "Zap Wand":                 SKPDItemData(302, "Item", ItemClassification.progression, "zap wand"),
    # "Smoke Bomb":               SKPDItemData(303, "Item", ItemClassification.progression, "smoke bomb"),
    # "War Horn":                 SKPDItemData(304, "Item", ItemClassification.progression, "war horn"),
    # "Red Troupple Chalice":     SKPDItemData(305, "Item", ItemClassification.progression, "red troupple chalice"),
    # "Blue Troupple Chalice":    SKPDItemData(306, "Item", ItemClassification.progression, "blue troupple chalice"),
    # "Wildcard":                 SKPDItemData(307, "Item", ItemClassification.progression, "wildcard"),
    # "Chronos Coin":             SKPDItemData(308, "Item", ItemClassification.progression, "chronos coin"),
    # "Ice Axe":                  SKPDItemData(309, "Item", ItemClassification.progression, "ice axe"),
    # "Fire Axe":                 SKPDItemData(310, "Item", ItemClassification.progression, "fire axe"),
    # "Shield":                   SKPDItemData(311, "Item", ItemClassification.progression, "shield"),
    # "Glitzemizer":              SKPDItemData(312, "Item", ItemClassification.progression, "glitzemizer"),
    # "Anchor":                   SKPDItemData(313, "Item", ItemClassification.progression, "anchor"),
    # "Copycard":                 SKPDItemData(314, "Item", ItemClassification.progression, "copycard"),
    # "Morphy Wand":              SKPDItemData(315, "Item", ItemClassification.progression, "magic wand"),
    # "Poison Dagger":            SKPDItemData(316, "Item", ItemClassification.progression, "poison dagger"),
    # "Flipwand":                 SKPDItemData(317, "Item", ItemClassification.progression, "flipwand"),
    # "Portable Sploder X":       SKPDItemData(318, "Item", ItemClassification.progression, "exploder X"),
    # "Portable Sploder +":       SKPDItemData(319, "Item", ItemClassification.progression, "exploder T"),
}

item_dict = {name: data.code for name, data in skpd_items.items()}